import { ChevronDown, ChevronUp, Mic, RotateCcw, Square, Volume2 } from 'lucide-react'
import { useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { usePronunciationPractice, validatePronunciationTarget } from '../hooks/usePronunciationPractice'
import type { PronunciationAttempt } from '../types'

export function PronunciationPage(){const[params]=useSearchParams();const source=params.get('text')??'',sourceId=params.get('sourceId'),sourceType=params.get('source')==='vocabulary'&&sourceId?'vocabulary':'custom';const practice=usePronunciationPractice(source,sourceType,sourceId);const validation=validatePronunciationTarget(practice.target);return <div className="space-y-6"><header><p className="eyebrow">LOCAL ACOUSTIC FEEDBACK</p><h1>Pronunciation Practice</h1><p className="muted max-w-2xl">Practice a word or short phrase and get local acoustic feedback.</p></header>
  <section className="glass rounded-3xl p-6 space-y-5"><label className="block font-medium" htmlFor="pronunciation-target">Target word or phrase</label><textarea id="pronunciation-target" value={practice.target} onChange={e=>practice.setTarget(e.target.value)} maxLength={160} rows={3} disabled={practice.state==='recording'||practice.state==='checking'||practice.state==='analyzing'} placeholder="I'm terrible at cooking." className="w-full rounded-2xl border border-white/10 bg-black/20 p-4"/><div className="flex justify-between text-xs muted"><span>{validation??'General American English reference · maximum 12 words'}</span><span>{practice.target.length}/160</span></div>
  {practice.state==='loading_engine'&&<Status text="Loading local pronunciation model…"/>}{practice.state==='recording'&&<Status text="Recording… Speak the target, then stop."/>}{practice.state==='checking'&&<Status text="Checking phrase…"/>}{practice.state==='analyzing'&&<Status text="Analyzing pronunciation…"/>}{practice.error&&<p role="alert" className="rounded-xl bg-red-500/10 p-3 text-sm text-red-200">{practice.error}</p>}
  <div className="flex flex-wrap gap-3">{practice.state==='recording'?<button className="button-primary" onClick={()=>void practice.stop()}><Square size={16}/> Stop recording</button>:<button className="button-primary" disabled={!!validation||!practice.engine?.ready||practice.state==='checking'||practice.state==='analyzing'} onClick={()=>void practice.start()}><Mic size={17}/> Record pronunciation</button>}{(practice.state==='checking'||practice.state==='analyzing')&&<button className="button-secondary" onClick={()=>void practice.cancel()}>Cancel</button>}<button className="button-secondary" disabled title="Hear Target is deferred until scoring calibration is complete."><Volume2 size={16}/> Hear target</button></div></section>
  {practice.result&&<ResultCard attempt={practice.result} retry={practice.retry}/>}<History items={practice.history}/>
  <p className="muted text-xs">This is a local pronunciation-practice estimate, not a language certification. Accent variation, microphone quality and background noise may affect the score.</p></div>}

function Status({text}:{text:string}){return <p role="status" className="rounded-xl bg-white/[.05] p-3 text-sm">{text}</p>}
function ResultCard({attempt,retry}:{attempt:PronunciationAttempt;retry:()=>void}){const[open,setOpen]=useState<number|null>(null);if(attempt.status==='content_mismatch')return <section className="glass rounded-3xl p-6"><h2>Try the phrase again</h2><p>The recording did not match the target closely enough. Try the phrase again.</p><button className="button-secondary" onClick={retry}><RotateCcw size={16}/> Try Again</button></section>;if(attempt.status!=='completed')return <section className="glass rounded-3xl p-6"><h2>No score available</h2><p className="muted">There was not enough reliable acoustic evidence. Please record again.</p><button className="button-secondary" onClick={retry}><RotateCcw size={16}/> Try Again</button></section>;return <section className="glass rounded-3xl p-6 space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">PRONUNCIATION PRACTICE SCORE</p><div className="text-5xl font-semibold">{Math.round(attempt.overallScore??0)}<span className="text-xl muted">/100</span></div></div><div><div className="text-sm">Confidence: <strong>{attempt.confidence}</strong></div><div className="muted text-sm">Target: {attempt.targetText}</div></div></div><div className="grid gap-3">{attempt.words.map(word=><div key={word.index} className="rounded-2xl border border-white/[.08]"><button className="flex w-full items-center justify-between p-4 text-left" aria-expanded={open===word.index} onClick={()=>setOpen(open===word.index?null:word.index)}><span className="font-medium">{word.word}</span><span className="flex items-center gap-2"><strong>{Math.round(word.score)}</strong>{open===word.index?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</span></button>{open===word.index&&<div className="border-t border-white/[.08] p-4"><p className="muted text-xs">Expected sounds: {word.expectedPhones.join(' · ')}</p><div className="grid gap-2">{word.phoneResults.map((phone,index)=><div key={`${phone.phone}-${index}`} className="rounded-xl bg-white/[.04] p-3"><div className="flex justify-between"><code>/{phone.phone}/</code><strong>{Math.round(phone.score)}</strong></div>{phone.closestAlternative&&<p className="muted mb-0 text-xs">This part was acoustically closer to /{phone.closestAlternative}/ than the target /{phone.phone}/.</p>}{phone.hint&&<p className="mb-0 text-sm">{phone.hint}</p>}</div>)}</div></div>}</div>)}</div><button className="button-secondary" onClick={retry}><RotateCcw size={16}/> Try Again</button></section>}
function History({items}:{items:PronunciationAttempt[]}){return <section><h2>Recent Practice</h2>{!items.length?<p className="muted">No pronunciation attempts yet.</p>:<div className="grid gap-2">{items.map(item=><div key={item.id} className="glass flex items-center justify-between rounded-2xl p-4"><div><div className="font-medium">{item.targetText}</div><div className="muted text-xs">{new Date(item.createdAt).toLocaleString()}</div></div><div className="text-right"><strong>{item.overallScore===null?'No score':Math.round(item.overallScore)}</strong><div className="muted text-xs">{item.confidence??item.status.replace('_',' ')}</div></div></div>)}</div>}</section>}
