import { useEffect, useState } from 'react'
import { BookOpenCheck, RotateCcw } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { AppCard, PageHeader, PageShell } from '../components/ProductUI'
import { getToeicPart6Result, getToeicPart6Review } from '../services/native'
import type { ToeicPart6Result, ToeicPart6ReviewSet } from '../types'

export function ToeicPart6ResultsPage(){const{id}=useParams();const sessionId=useParams().sessionId??id;const nav=useNavigate();const[result,setResult]=useState<ToeicPart6Result|null>(null);const[review,setReview]=useState<ToeicPart6ReviewSet[]|null>(null);const[error,setError]=useState<string|null>(null);const load=()=>{if(!sessionId)return;setError(null);void Promise.all([getToeicPart6Result(sessionId),getToeicPart6Review(sessionId,true)]).then(([a,b])=>{setResult(a);setReview(b)}).catch(x=>setError(x instanceof Error?x.message:String(x)))};useEffect(load,[sessionId]);if(error)return <ErrorState message={error} onRetry={load}/>;if(!result||!review)return <LoadingState label="Building deterministic Part 6 results…"/>;const bars=(title:string,items:typeof result.skillBreakdown)=><AppCard><h2 className="section-title">{title}</h2>{items.map(x=><div className="toeic-breakdown-row" key={x.label}><span>{x.label.replaceAll('_',' ')}</span><progress value={x.correct} max={x.total}/><b>{x.correct}/{x.total}</b></div>)}</AppCard>;return <PageShell width="wide"><PageHeader eyebrow="Part 6 complete" title={`${result.correct} / 16 · ${result.accuracy}%`} description="Raw Part 6 performance. Your first answers remain final."/><div className="toeic-result-grid">{bars('Reading skills',result.skillBreakdown)}{bars('Difficulty',result.difficultyBreakdown)}{bars('Document types',result.documentBreakdown)}</div><AppCard className="mt-4"><p>{result.scoreMessage}</p><div className="toeic-result-actions"><button className="button-primary" onClick={()=>document.getElementById('part6-review')?.scrollIntoView({behavior:'smooth'})}><RotateCcw/>Review mistakes</button><button className="button-secondary" onClick={()=>nav('/toeic')}><BookOpenCheck/>Back to TOEIC</button></div></AppCard><section id="part6-review" className="mt-4"><PageHeader eyebrow="Review mistakes" title={`${review.length} text set${review.length===1?'':'s'} to revisit`} description="Completed texts and author-controlled explanations are shown only after completion."/>{review.map(set=><AppCard key={set.textSetId} className="mt-3"><h2>{set.title}</h2><div className="toeic-p6-document">{set.feedback.completedText}</div>{set.feedback.questions.filter(q=>!q.isCorrect).map(q=><article className="toeic-feedback wrong" key={q.blankId}><h3>Question {q.questionNumber}: {q.selectedChoice} → {q.correctChoice}</h3><p>{q.correctExplanation}</p><p>{q.selectedDistractorExplanation}</p><small>{q.skillCategory.replaceAll('_',' ')}</small></article>)}</AppCard>)}</section></PageShell>}
