import { BookOpenCheck, ChevronRight, Headphones } from "lucide-react";
import { useEffect, useState } from "react";
import { useNavigate, useParams, useSearchParams } from "react-router-dom";
import { ErrorState, LoadingState } from "../components/PageState";
import { AppCard, InlineNotice, PageHeader, PageShell } from "../components/ProductUI";
import { ToeicAggregatePanel } from "../components/ToeicAggregatePanel";
import { getToeicFullLr, getToeicFullLrAggregate, startToeicFullLr } from "../services/native";
import type { ToeicFullLrAggregate, ToeicFullLrSession } from "../types";

export function ToeicFullLrPage() {
  const { id } = useParams(); const nav = useNavigate(); const [search] = useSearchParams(); const requested = search.get("family")?.toUpperCase(); const family: "A" | "B" | "C" = requested === "B" || requested === "C" ? requested : "A"; const [data, setData] = useState<ToeicFullLrSession | null>(null); const [aggregate, setAggregate] = useState<ToeicFullLrAggregate | null>(null); const [mistakes, setMistakes] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = () => { setError(null); void (id ? getToeicFullLr(id) : startToeicFullLr(family)).then((s) => { setData(s); if (!id) nav(`/toeic/full/${s.sessionId}`, { replace: true }); }).catch((x) => setError(x instanceof Error ? x.message : String(x))); }; useEffect(load, [id, family]);
  const loadReview = (only: boolean) => { if (!data) return; setMistakes(only); void getToeicFullLrAggregate(data.sessionId, only).then(setAggregate).catch((x) => setError(String(x))); };
  if (error) return <ErrorState message={error} onRetry={load} />; if (!data) return <LoadingState label="Restoring Full TOEIC L&R…" />; const done = data.status === "completed";
  return <PageShell width="wide"><PageHeader eyebrow={`Unofficial · Untimed · Simulation Mode · Family ${data.family}`} title={done ? `Estimated total: ${data.totalEstimate}` : "Full TOEIC Listening & Reading"} description={done ? `${data.totalRaw}/200 raw · Practice range ${data.rangeLow}–${data.rangeHigh}` : "Listening 100 + Reading 100 · Pause and resume across sections"} /><InlineNotice tone="info">{data.disclaimer}</InlineNotice><div className="toeic-result-grid"><AppCard><Headphones /><h2>Listening</h2><p>{data.listeningRaw ?? 0}/100 raw</p>{data.listeningEstimate && <strong>Estimated {data.listeningEstimate}</strong>}</AppCard><AppCard><BookOpenCheck /><h2>Reading</h2><p>{data.readingRaw ?? 0}/100 raw</p>{data.readingEstimate && <strong>Estimated {data.readingEstimate}</strong>}</AppCard></div>{!done ? <button className="button-primary mt-4" onClick={() => nav(data.currentSection === "listening" ? data.listeningRoute : data.readingRoute)}>Continue {data.currentSection}<ChevronRight /></button> : <AppCard><h2>Total result</h2><p>{data.totalRaw}/200 raw · Estimated {data.totalEstimate}/990</p><div className="button-row"><button className="button-primary" onClick={() => loadReview(true)}>Review Mistakes</button><button className="button-secondary" onClick={() => loadReview(false)}>Review All</button></div>{aggregate && <><h3>Listening</h3><ToeicAggregatePanel key={`l-${mistakes}`} parts={aggregate.listening} label="Listening aggregate" /><h3>Reading</h3><ToeicAggregatePanel key={`r-${mistakes}`} parts={aggregate.reading} label="Reading aggregate" /></>}</AppCard>}</PageShell>;
}
