import { BookOpenCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useReviewOverview } from '../hooks/useReviewData'
import { formatLocalDate } from '../utils/format'

export function ReviewOverviewCard({ activity=false }:{activity?:boolean}){
 const query=useReviewOverview();if(query.loading)return <section className="glass rounded-[22px] p-5 text-sm muted">Loading Review activity…</section>;if(query.error||!query.data)return <section className="glass rounded-[22px] p-5"><p className="text-sm text-red-200">{query.error??'Review data unavailable.'}</p><button onClick={query.reload} className="rounded-full border border-white/15 px-4 py-2 text-xs">Retry</button></section>;
 const value=query.data;
 if(activity)return <section className="glass rounded-[22px] p-5" aria-label="Review Activity"><div className="flex items-center gap-2"><BookOpenCheck size={17} className="text-[var(--accent)]"/><h2 className="m-0 text-base">Review Activity</h2></div><div className="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Sessions completed" value={value.reviewHistory.completedSessionCount}/><Metric label="Items reviewed" value={value.reviewHistory.reviewedItemCount}/><Metric label="Vocabulary" value={value.reviewHistory.vocabularyReviewed}/><Metric label="Mistakes" value={value.reviewHistory.mistakesReviewed}/><Metric label="Last review" value={value.reviewHistory.lastReviewAt?formatLocalDate(value.reviewHistory.lastReviewAt):'None yet'}/></div><p className="muted mb-0 mt-3 text-xs">Review activity is separate from language scores and does not produce XP.</p></section>;
 return <section className="glass rounded-[22px] p-5" aria-label="Suggested Review"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="muted mb-1 text-[10px] uppercase tracking-widest">Suggested Review</p><h2 className="m-0 text-base">What is worth reviewing next?</h2></div><Link to={value.activeSession?`/review/session/${value.activeSession.id}`:'/review'} className="rounded-full bg-[var(--accent)] px-4 py-2 text-xs font-semibold text-black no-underline">{value.activeSession?'Resume Review':'Start Review'}</Link></div><div className="mt-4 grid grid-cols-2 gap-3"><Metric label="Vocabulary items" value={value.vocabulary.totalEligibleCount}/><Metric label="Recurring mistakes" value={value.recurringMistakes.confirmedCount}/></div>{value.activeSession&&<p className="muted mb-0 mt-3 text-xs">{value.activeSession.reviewedItemCount}/{value.activeSession.actualItemCount} items saved.</p>}</section>
}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-white/[.035] p-3"><strong className="block text-lg">{value}</strong><span className="muted text-[10px] uppercase tracking-wider">{label}</span></div>}
