import { ArrowLeft, Check, Eye, Flag, RotateCcw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { abandonReviewSession, getReviewSession, submitReviewItem } from '../services/native'
import type { ReviewOutcome, ReviewSession } from '../types'
import { notifyLearningDataChanged } from '../utils/learningData'
import { notifyReviewDataChanged } from '../utils/reviewData'

export function ReviewSessionPage(){const{sessionId=''}=useParams();const navigate=useNavigate();const[session,setSession]=useState<ReviewSession|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[revealed,setRevealed]=useState(false);const[busy,setBusy]=useState(false);const[confirmAbandon,setConfirmAbandon]=useState(false);
 useEffect(()=>{let disposed=false;setLoading(true);void getReviewSession(sessionId).then(value=>{if(!disposed){if(!value)throw new Error('Review session not found.');setSession(value)}}).catch(e=>{if(!disposed)setError(e instanceof Error?e.message:String(e))}).finally(()=>{if(!disposed)setLoading(false)});return()=>{disposed=true}},[sessionId]);
 useEffect(()=>setRevealed(false),[session?.currentItem?.id]);
 const submit=async(outcome:ReviewOutcome)=>{if(!session?.currentItem)return;setBusy(true);setError(null);try{const result=await submitReviewItem(session.id,session.currentItem.id,outcome);setSession(result.session);notifyReviewDataChanged();if(result.vocabularyStatusChanged)notifyLearningDataChanged()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const abandon=async()=>{if(!session)return;setBusy(true);try{await abandonReviewSession(session.id);notifyReviewDataChanged();navigate('/review')}catch(e){setError(e instanceof Error?e.message:String(e));setBusy(false)}};
 if(loading)return <LoadingState label="Loading saved Review session…"/>;if(error&&!session)return <ErrorState message={error} onRetry={()=>window.location.reload()}/>;if(!session)return null;
 if(session.status==='completed')return <><header className="mb-7"><p className="muted mb-2 text-xs uppercase tracking-[.18em]">Review complete</p><h1 className="m-0 text-3xl">Session saved</h1><p className="muted text-sm">No score was calculated. Your explicit review choices were saved locally.</p></header><section className="glass rounded-[28px] p-6"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Summary label="Items reviewed" value={session.completionSummary?.itemsReviewed??0}/><Summary label="Vocabulary" value={session.completionSummary?.vocabularyReviewed??0}/><Summary label="Mistakes" value={session.completionSummary?.mistakesReviewed??0}/><Summary label="Marked Learning" value={session.completionSummary?.vocabularyMarkedLearning??0}/><Summary label="Marked Known" value={session.completionSummary?.vocabularyMarkedKnown??0}/></div><Link to="/review" className="mt-6 inline-flex rounded-full bg-[var(--accent)] px-5 py-3 font-semibold text-black no-underline">Back to Review</Link></section></>;
 const item=session.currentItem!;return <><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="muted mb-2 text-xs uppercase tracking-[.18em]">{session.reviewedItemCount+1} / {session.actualItemCount}</p><h1 className="m-0 text-2xl">Review Session</h1></div><Link to="/review" className="flex items-center gap-2 rounded-full border border-white/15 px-4 py-2 text-sm text-white no-underline"><ArrowLeft size={15}/>Exit Review</Link></header><div className="mb-6 h-2 overflow-hidden rounded-full bg-white/[.07]" aria-label={`${session.reviewedItemCount} of ${session.actualItemCount} reviewed`}><div className="h-full bg-[var(--accent)]" style={{width:`${session.reviewedItemCount/session.actualItemCount*100}%`}}/></div>
 <section className="glass mx-auto max-w-3xl rounded-[30px] p-6 md:p-10" aria-label="Current review item">{item.type==='vocabulary'?<><p className="muted text-xs uppercase tracking-widest">Word / Phrase</p><h2 className="text-3xl">{item.content.displayText}</h2>{item.content.example&&<blockquote className="m-0 mt-5 rounded-2xl bg-white/[.035] p-4 text-sm">“{item.content.example}”</blockquote>}{revealed&&<div className="mt-6 rounded-2xl border border-[var(--accent)]/20 bg-[var(--accent)]/[.04] p-5"><p className="muted mt-0 text-xs uppercase tracking-wider">Meaning</p><p className="mb-0 text-lg">{item.content.meaning}</p></div>}</>:<><p className="muted text-xs uppercase tracking-widest">Original</p><h2 className="text-2xl">{item.content.original}</h2>{revealed&&<div className="mt-6 space-y-4"><div className="rounded-2xl border border-[var(--accent)]/20 bg-[var(--accent)]/[.04] p-5"><p className="muted mt-0 text-xs uppercase tracking-wider">Corrected</p><p className="mb-0 text-lg">{item.content.corrected}</p></div><div><p className="muted mb-1 text-xs uppercase tracking-wider">Why</p><p className="m-0 text-sm">{item.content.explanation}</p></div></div>}</>}
 {!revealed?<button autoFocus onClick={()=>setRevealed(true)} className="mt-7 flex items-center gap-2 rounded-full bg-[var(--accent)] px-6 py-3 font-semibold text-black"><Eye size={17}/> {item.type==='vocabulary'?'Reveal meaning':'Reveal correction'}</button>:item.type==='vocabulary'?<div className="mt-7 flex flex-wrap gap-3"><Action disabled={busy} onClick={()=>void submit('keep_practicing')} label="Keep Practicing"/><Action disabled={busy} onClick={()=>void submit('mark_learning')} label="Mark as Learning"/><Action primary disabled={busy} onClick={()=>void submit('mark_known')} label="Mark as Known"/></div>:<div className="mt-7 flex flex-wrap gap-3"><Action disabled={busy} onClick={()=>void submit('review_again')} label="Review Again Later" icon={<RotateCcw size={15}/>}/><Action primary disabled={busy} onClick={()=>void submit('reviewed')} label="Reviewed" icon={<Check size={15}/>}/></div>}{error&&<p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}</section>
 <section className="mx-auto mt-5 max-w-3xl"><button onClick={()=>setConfirmAbandon(true)} className="flex items-center gap-2 bg-transparent text-xs text-red-200"><Flag size={14}/>Abandon Review</button>{confirmAbandon&&<div role="alert" className="mt-3 rounded-2xl border border-red-300/20 p-4 text-sm"><p className="mt-0">Reviewed items remain in history. Unreviewed items will not count.</p><div className="flex gap-3"><button disabled={busy} onClick={()=>void abandon()} className="rounded-full border border-red-300/30 px-4 py-2 text-red-200">Confirm abandon</button><button onClick={()=>setConfirmAbandon(false)} className="rounded-full border border-white/15 px-4 py-2">Keep reviewing</button></div></div>}</section></>}
function Action({label,onClick,disabled,primary=false,icon}:{label:string;onClick:()=>void;disabled:boolean;primary?:boolean;icon?:React.ReactNode}){return <button disabled={disabled} onClick={onClick} className={`flex items-center gap-2 rounded-full px-5 py-3 text-sm font-semibold disabled:opacity-50 ${primary?'bg-[var(--accent)] text-black':'border border-white/15'}`}>{icon}{label}</button>}
function Summary({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white/[.035] p-4"><strong className="text-xl">{value}</strong><span className="muted mt-1 block text-xs">{label}</span></div>}
