// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { ReviewSession } from '../types'
const mocks=vi.hoisted(()=>({get:vi.fn(),submit:vi.fn(),abandon:vi.fn(),notifyReview:vi.fn(),notifyLearning:vi.fn()}))
vi.mock('../services/native',()=>({getReviewSession:mocks.get,submitReviewItem:mocks.submit,abandonReviewSession:mocks.abandon}))
vi.mock('../utils/reviewData',()=>({notifyReviewDataChanged:mocks.notifyReview}))
vi.mock('../utils/learningData',()=>({notifyLearningDataChanged:mocks.notifyLearning}))
import { ReviewSessionPage } from './ReviewSessionPage'
const vocabulary:ReviewSession={id:'s',status:'in_progress',mode:'vocabulary',requestedItemCount:5,actualItemCount:2,reviewedItemCount:0,currentIndex:0,startedAt:'2026-08-21',completedAt:null,currentItem:{type:'vocabulary',id:'i',sequenceIndex:0,reviewed:false,reviewOutcome:null,reviewedAt:null,content:{schemaVersion:1,displayText:'terrible at',meaning:'very bad at a skill',example:'I am terrible at cooking.',statusAtStart:'learning',lessonCount:2,occurrenceCount:3}},completionSummary:null}
const mistake:ReviewSession={...vocabulary,mode:'mistakes',actualItemCount:1,currentItem:{type:'recurring_mistake',id:'m',sequenceIndex:0,reviewed:false,reviewOutcome:null,reviewedAt:null,content:{schemaVersion:1,title:'Preposition after terrible',category:'preposition',original:'I am terrible cooking.',corrected:'I am terrible at cooking.',explanation:'Use at before the activity.',lessonCount:2,occurrenceCount:2}}}
function view(){return render(<MemoryRouter initialEntries={['/review/session/s']}><Routes><Route path="/review/session/:sessionId" element={<ReviewSessionPage/>}/><Route path="/review" element={<div>Review landing</div>}/></Routes></MemoryRouter>)}
describe('ReviewSessionPage',()=>{beforeEach(()=>{vi.clearAllMocks();mocks.get.mockResolvedValue(vocabulary);mocks.abandon.mockResolvedValue({...vocabulary,status:'abandoned'})});afterEach(cleanup)
 it('reveals vocabulary and autosaves an explicit status outcome',async()=>{mocks.submit.mockResolvedValue({session:{...vocabulary,reviewedItemCount:1},vocabularyStatusChanged:true});view();expect(await screen.findByText('terrible at')).toBeInTheDocument();expect(screen.queryByText('very bad at a skill')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Reveal meaning'}));expect(screen.getByText('very bad at a skill')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Mark as Known'}));await waitFor(()=>expect(mocks.submit).toHaveBeenCalledWith('s','i','mark_known'));expect(mocks.notifyLearning).toHaveBeenCalled()})
 it('reveals a real mistake without vocabulary outcomes',async()=>{mocks.get.mockResolvedValue(mistake);view();expect(await screen.findByText('I am terrible cooking.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Reveal correction'}));expect(screen.getByText('I am terrible at cooking.')).toBeInTheDocument();expect(screen.getByText('Use at before the activity.')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Reviewed'})).toBeInTheDocument();expect(screen.queryByRole('button',{name:'Mark as Known'})).not.toBeInTheDocument()})
 it('shows a score-free completion summary',async()=>{mocks.get.mockResolvedValue({...vocabulary,status:'completed',reviewedItemCount:2,currentItem:null,completedAt:'2026-08-21',completionSummary:{itemsReviewed:2,vocabularyReviewed:2,mistakesReviewed:0,vocabularyMarkedLearning:1,vocabularyMarkedKnown:1}});view();expect(await screen.findByText('Session saved')).toBeInTheDocument();expect(screen.getByText(/No score was calculated/)).toBeInTheDocument();expect(screen.getByText('Marked Known')).toBeInTheDocument()})
 it('requires confirmation before abandoning',async()=>{view();await screen.findByText('terrible at');fireEvent.click(screen.getByRole('button',{name:'Abandon Review'}));expect(screen.getByRole('button',{name:'Confirm abandon'})).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Confirm abandon'}));await waitFor(()=>expect(mocks.abandon).toHaveBeenCalledWith('s'));expect(await screen.findByText('Review landing')).toBeInTheDocument()})
})
