import { ArrowLeft, Check, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ConfirmationDialog } from '../components/ConfirmationDialog'
import { ErrorState, LoadingState } from '../components/PageState'
import { PageHeader, PageShell } from '../components/ProductUI'
import { abandonGuidedLesson, completeGuidedLessonStage, getGuidedLessonSession, skipGuidedLessonStage } from '../services/native'
import type { GuidedLessonSession, TheoryBlock } from '../types'

export function GuidedLessonSessionPage(){const{sessionId=''}=useParams();const navigate=useNavigate();const[session,setSession]=useState<GuidedLessonSession|null|undefined>();const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[confirmAbandon,setConfirmAbandon]=useState(false);const load=useCallback(async()=>{setError(null);try{setSession(await getGuidedLessonSession(sessionId))}catch(value){setError(value instanceof Error?value.message:String(value))}},[sessionId]);useEffect(()=>{void load()},[load]);if(session===undefined&&!error)return <LoadingState label="Restoring Guided Lesson…"/>;if(error&&!session)return <ErrorState message={error} onRetry={()=>void load()}/>;if(!session)return <PageShell><PageHeader title="Guided lesson session not found" description="This saved session does not exist."/><Link className="button-secondary inline-flex no-underline" to="/guided-lessons">Back to Guided Lessons</Link></PageShell>;
const act=async(kind:'complete'|'skip')=>{if(!session.activeStage||busy)return;setBusy(true);setError(null);try{const next=kind==='complete'?await completeGuidedLessonStage(session.id,session.activeStage.stageId):await skipGuidedLessonStage(session.id,session.activeStage.stageId);setSession(next)}catch(value){setError(value instanceof Error?value.message:String(value))}finally{setBusy(false)}};const abandon=async()=>{setBusy(true);setError(null);try{await abandonGuidedLesson(session.id);navigate('/guided-lessons')}catch(value){setError(value instanceof Error?value.message:String(value))}finally{setBusy(false)}};
if(session.status==='completed')return <PageShell width="narrow"><section className="glass rounded-[28px] p-8 text-center"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-emerald-400/10 text-emerald-300"><Check size={28}/></div><p className="eyebrow mt-5">Guided Lesson complete</p><h1 className="page-title">{session.title}</h1><p className="page-description">You completed all {session.stageCount} stages. This foundation records completion only—there is no score, XP or analysis.</p><Link className="button-primary mt-4 inline-flex no-underline" to="/guided-lessons">Back to Guided Lessons</Link></section></PageShell>;
if(session.status!=='in_progress')return <PageShell width="narrow"><PageHeader eyebrow="Saved Guided Lesson" title={session.title} description={`This session is ${session.status}. Saved sessions cannot be changed.`}/><Link className="button-secondary inline-flex no-underline" to="/guided-lessons">Back to Guided Lessons</Link></PageShell>;
const stage=session.activeStage;return <PageShell width="standard"><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><Link to="/guided-lessons" className="muted inline-flex items-center gap-2 text-sm no-underline"><ArrowLeft size={15}/>Guided Lessons</Link><button type="button" className="button-secondary" onClick={()=>setConfirmAbandon(true)}><X size={15}/>Abandon Lesson</button></div><header className="glass rounded-[24px] p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">{session.cefrBand} · Guided Lesson</p><h1 className="m-0 text-2xl">{session.title}</h1></div><strong aria-live="polite" className="text-sm">{session.progressPercent}% complete</strong></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-white/[.06]" role="progressbar" aria-label="Lesson progress" aria-valuemin={0} aria-valuemax={100} aria-valuenow={session.progressPercent}><div className="h-full bg-[var(--accent)] transition-[width]" style={{width:`${session.progressPercent}%`}}/></div><ol aria-label="Lesson stages" className="mt-4 flex gap-2 overflow-x-auto p-0">{session.stages.map(item=><li key={item.stageId} aria-current={item.status==='active'?'step':undefined} className={`min-w-28 rounded-xl border px-3 py-2 text-xs ${item.status==='active'?'border-[var(--accent)]/45 bg-[var(--accent)]/[.06]':'border-white/10'}`}><span className="muted">{item.sequenceIndex+1}</span><div className="mt-1 truncate">{item.title}</div></li>)}</ol></header>
{!stage?<section className="glass mt-5 rounded-[24px] p-6"><h2 className="section-title">Stage unavailable</h2><p className="page-description">The saved stage cannot be rendered by this engine. Your session remains preserved.</p></section>:<section className="glass mt-5 rounded-[28px] p-5 md:p-8" aria-labelledby="active-stage-title"><p className="eyebrow">Stage {stage.sequenceIndex+1} of {session.stageCount}</p><h2 id="active-stage-title" className="page-title">{stage.title}</h2><p className="page-description">{stage.instructions}</p>{stage.content.kind==='theory'?<TheoryContent blocks={stage.content.blocks}/>:<div className="mt-6 grid gap-4 sm:grid-cols-2">{stage.content.items.map(item=><article key={item.itemId} className="rounded-2xl border border-white/10 bg-white/[.035] p-5"><h3 className="m-0 text-xl text-[var(--accent)]">{item.term}</h3><p className="mt-2 text-sm">{item.meaning}</p><p className="muted mb-0 text-sm italic">“{item.example}”</p>{item.imageAssetId&&<p className="muted mb-0 mt-3 text-xs">Visual reference included in the local package.</p>}</article>)}</div>}<div className="mt-7 flex flex-wrap gap-3"><button type="button" className="button-primary" disabled={busy} onClick={()=>void act('complete')}>{busy?'Saving…':'Continue'}</button>{!stage.required&&<button type="button" className="button-secondary" disabled={busy} onClick={()=>void act('skip')}>Skip optional stage</button>}</div>{error&&<p role="alert" className="mt-4 text-sm text-red-200">{error}</p>}</section>}<ConfirmationDialog open={confirmAbandon} title="Abandon this Guided Lesson?" description="Progress will be saved in history, but this session cannot be resumed after it is abandoned." confirmLabel="Abandon Lesson" danger busy={busy} onClose={()=>setConfirmAbandon(false)} onConfirm={()=>void abandon()}/></PageShell>}

function TheoryContent({blocks}:{blocks:TheoryBlock[]}){return <div className="mt-6 space-y-4">{blocks.map((block,index)=>{if(block.type==='paragraph')return <p key={index} className="leading-7">{block.text}</p>;if(block.type==='bullet_list')return <ul key={index} className="space-y-2 pl-5">{block.items?.map(item=><li key={item}>{item}</li>)}</ul>;if(block.type==='example')return <figure key={index} className="rounded-2xl bg-white/[.04] p-5"><blockquote className="m-0 text-lg">{block.english}</blockquote>{block.explanation&&<figcaption className="muted mt-2 text-sm">{block.explanation}</figcaption>}</figure>;return <aside key={index} className="rounded-2xl border border-[var(--accent)]/20 bg-[var(--accent)]/[.04] p-5">{block.title&&<h3 className="mt-0 text-base">{block.title}</h3>}<p className="mb-0 text-sm leading-6">{block.text}</p></aside>})}</div>}
