import { BookOpenCheck, Clock3, Play, RotateCcw } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { PageHeader, PageShell } from '../components/ProductUI'
import { useGuidedLessonLibrary } from '../hooks/useGuidedLessons'
import { humanize } from '../utils/format'

export function GuidedLessonsPage(){const query=useGuidedLessonLibrary();const navigate=useNavigate();if(query.loading)return <LoadingState label="Loading Guided Lessons locally…"/>;if(query.error||!query.data)return <ErrorState message={query.error??'Guided Lessons are unavailable.'} onRetry={query.reload}/>;const{overview,lessons,recent}=query.data;return <PageShell width="wide"><PageHeader eyebrow="Local lesson packages" title="Guided Lessons" description="Structured, offline lessons that progress one stage at a time. Content and session state stay on this computer."/>
{overview.activeSession&&<section className="mb-5 rounded-[22px] border border-[var(--accent)]/25 bg-[var(--accent)]/[.05] p-5"><p className="eyebrow">Lesson in progress</p><h2 className="section-title">{overview.activeSession.title}</h2><p className="muted text-sm">Stage {overview.activeSession.currentStageIndex+1} of {overview.activeSession.stageCount} · {overview.activeSession.progressPercent}% complete</p><button className="button-primary" onClick={()=>navigate(`/guided-lessons/session/${overview.activeSession!.id}`)}>Resume Lesson</button></section>}
{lessons.length===0?<section className="glass rounded-[28px] p-8 text-center"><BookOpenCheck aria-hidden="true" className="mx-auto text-[var(--accent)]"/><h2 className="section-title mt-4">No guided lessons are installed yet.</h2><p className="page-description mx-auto max-w-xl">Install a valid local lesson package to make it available here. Free Conversation remains available from New Lesson.</p></section>:<section aria-labelledby="guided-library"><h2 id="guided-library" className="section-title">Lesson library</h2><div className="mt-4 grid gap-4 lg:grid-cols-2">{lessons.map(lesson=><article key={lesson.lessonId} className="glass rounded-[24px] p-5"><div className="flex flex-wrap items-center gap-2 text-xs"><span className="rounded-full bg-[var(--accent)]/10 px-3 py-1 text-[var(--accent)]">{lesson.cefrBand}</span><span className="muted flex items-center gap-1"><Clock3 size={13}/>{lesson.estimatedMinutes} min</span><span className="muted">{lesson.stageCount} stages</span></div><h3 className="mt-4 text-lg">{lesson.title}</h3><p className="muted text-sm">{lesson.description}</p><div className="flex flex-wrap gap-2">{lesson.tags.map(tag=><span key={tag} className="rounded-full border border-white/10 px-2 py-1 text-xs muted">{tag}</span>)}</div><Link className="button-secondary mt-5 inline-flex no-underline" to={`/guided-lessons/${lesson.lessonId}`}>View Lesson</Link>{!lesson.startable&&<p role="status" className="mt-3 text-xs text-amber-200">Some lesson stages are not available in this engine.</p>}</article>)}</div></section>}
{recent.length>0&&<section className="glass mt-5 rounded-[24px] p-5"><div className="flex items-center gap-2"><RotateCcw size={16} className="text-[var(--accent)]"/><h2 className="m-0 text-base">Recent Guided Lessons</h2></div><div className="mt-4 space-y-2">{recent.map(session=><button key={session.id} className="flex w-full items-center justify-between gap-3 rounded-xl bg-white/[.035] p-3 text-left text-sm" onClick={()=>navigate(`/guided-lessons/session/${session.id}`)}><span>{session.title}</span><span className="muted">{humanize(session.status)} · {session.progressPercent}%</span></button>)}</div></section>}<p className="muted mt-4 flex items-center gap-2 text-xs"><Play size={13}/>Guided Lessons do not award scores, XP or achievements in this foundation.</p></PageShell>}
