// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { cleanup, render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { Course, CurriculumCatalog } from '../types'

const getCourseCatalog = vi.fn()
const startGuidedLesson = vi.fn()
vi.mock('../services/native', () => ({ getCourseCatalog: (...args:unknown[])=>getCourseCatalog(...args), startGuidedLesson: (...args:unknown[])=>startGuidedLesson(...args) }))
import { CoursePage } from './CoursePage'

const progress=(total:number,completed=0,inProgress=0)=>({totalLessons:total,completedLessons:completed,inProgressLessons:inProgress,percent:total?Math.round(completed*100/total):0})
const lesson=(id:string,status:'not_started'|'in_progress'|'completed'='not_started')=>({lessonId:id,contentVersion:2,title:`Lesson ${id}`,description:'A real resolved TEST lesson.',cefrBand:'A1' as const,estimatedMinutes:5,objectives:['Practice safely.'],startable:true,unavailableReasons:[],status,completionCount:status==='completed'?1:0,hasUpdatedContentAvailable:status==='completed',activeSessionId:status==='in_progress'?'active-1':null,activeSessionContentVersion:status==='in_progress'?1:null})
function course(levels=['A1','A2','B1','B2','C1','C2']):Course{return {curriculumId:'test-course',curriculumVersion:1,curriculumHash:'a'.repeat(64),title:'TEST English Course',description:'Structured test content.',targetLanguage:'en',referenceLocale:'en-US',suggestedLevel:'B1',placementConfidence:'high',targetLevel:'B2',progress:progress(levels.length,1),levels:levels.map((cefr,index)=>({levelId:cefr.toLowerCase(),cefrLevel:cefr as Course['levels'][number]['cefrLevel'],title:`${cefr} title`,description:`${cefr} description`,objectives:['Objective'],recommended:cefr==='B1',target:cefr==='B2',progress:progress(1,index===0?1:0),units:[{unitId:`${cefr.toLowerCase()}-unit`,title:`${cefr} Unit`,description:'Unit description',objectives:['Unit objective'],skillFocus:['speaking'],grammarTopics:['verb be'],vocabularyTopics:['names'],communicativeFunctions:['introducing yourself'],progress:progress(1,index===0?1:0),lessons:[lesson(`${cefr.toLowerCase()}-lesson`,index===0?'completed':'not_started')]}]}))}}
function catalog(courses:Course[],activeSession:CurriculumCatalog['activeSession']=null):CurriculumCatalog{return {registryVersion:1,progressVersion:1,recommendationVersion:2,taxonomyVersion:1,publishedCurriculumCount:courses.length,activeSession,continueLearning:{kind:activeSession?'resume_lesson':'choose_level',title:'Continue Learning',description:'Next deterministic step.',actionLabel:activeSession?'Resume Lesson':'Choose a Level',curriculumId:courses[0]?.curriculumId??null,levelId:null,unitId:null,lessonId:activeSession?.lessonId??null,sessionId:activeSession?.sessionId??null},practiceSuggestion:null,curricula:courses}}
function renderPath(path:string){return render(<MemoryRouter initialEntries={[path]}><Routes><Route path="/course" element={<CoursePage/>}/><Route path="/course/:curriculumId" element={<CoursePage/>}/><Route path="/course/:curriculumId/:levelId" element={<CoursePage/>}/><Route path="/course/:curriculumId/:levelId/:unitId" element={<CoursePage/>}/><Route path="/guided-lessons/session/:sessionId" element={<div>Runner</div>}/></Routes></MemoryRouter>)}

beforeEach(()=>{getCourseCatalog.mockReset();startGuidedLesson.mockReset()})
afterEach(cleanup)
describe('CoursePage',()=>{
  it('shows an honest empty state without fake production content',async()=>{getCourseCatalog.mockResolvedValue(catalog([]));renderPath('/course');expect(await screen.findByRole('heading',{name:'No course content is installed yet.'})).toBeInTheDocument();expect(screen.getByRole('link',{name:'Open Guided Lessons'})).toHaveAttribute('href','/guided-lessons')})
  it('renders six levels in canonical order with recommendation and target as non-locking badges',async()=>{getCourseCatalog.mockResolvedValue(catalog([course()]));renderPath('/course');expect(await screen.findByRole('heading',{name:'TEST English Course'})).toBeInTheDocument();const links=screen.getAllByRole('link',{name:/Explore/}).map(node=>node.textContent);expect(links).toEqual(['Explore A1','Explore A2','Explore B1','Explore B2','Explore C1','Explore C2']);expect(screen.getByText('Suggested from your placement')).toBeInTheDocument();expect(screen.getByText('Your target')).toBeInTheDocument();expect(screen.queryByText(/complete .* unlock/i)).not.toBeInTheDocument()})
  it('keeps a B1 Placement honest when the installed Course contains only A1 and A2',async()=>{getCourseCatalog.mockResolvedValue(catalog([course(['A1','A2'])]));renderPath('/course');expect(await screen.findByText('Placement level is outside this Course')).toBeInTheDocument();expect(screen.getByText(/never restricts Course access/)).toBeInTheDocument();expect(screen.queryByText('Suggested from your placement')).not.toBeInTheDocument()})
  it('renders generic unit metadata, accessible progress and real lesson statuses',async()=>{const value=course(['A1']);value.levels[0].units[0].lessons=[lesson('one','not_started'),lesson('two','in_progress'),lesson('three','completed')];value.levels[0].units[0].progress=progress(3,1,1);getCourseCatalog.mockResolvedValue(catalog([value],{sessionId:'active-1',lessonId:'two',contentVersion:1}));renderPath('/course/test-course/a1/a1-unit');expect(await screen.findByRole('heading',{name:'A1 Unit'})).toBeInTheDocument();expect(screen.getByText('Grammar topics')).toBeInTheDocument();expect(screen.getByRole('progressbar',{name:'A1 Unit progress'})).toHaveAttribute('aria-valuenow','33');expect(screen.getByText('Not started')).toBeInTheDocument();expect(screen.getByText('In progress')).toBeInTheDocument();expect(screen.getByText('Completed')).toBeInTheDocument();expect(screen.getByRole('link',{name:/Resume Lesson/})).toHaveAttribute('href','/guided-lessons/session/active-1')})
  it('handles multiple curricula and never silently abandons an active lesson',async()=>{const first=course(['A1']);const second={...course(['B1']),curriculumId:'second',title:'Second Course'};getCourseCatalog.mockResolvedValue(catalog([first,second],{sessionId:'other-session',lessonId:'outside',contentVersion:1}));const view=renderPath('/course');expect(await screen.findByRole('heading',{name:'Choose a course'})).toBeInTheDocument();expect(screen.getAllByRole('link',{name:'Open Course'})).toHaveLength(2);view.unmount();renderPath('/course/test-course/a1/a1-unit');expect(await screen.findByRole('link',{name:'Resume existing lesson'})).toHaveAttribute('href','/guided-lessons/session/other-session');expect(screen.getByRole('button',{name:'Review Update'})).toBeDisabled();expect(startGuidedLesson).not.toHaveBeenCalled()})
})
