import { BarChart3,BookOpen,CheckCircle2,Headphones,RotateCcw } from 'lucide-react'
import { useEffect,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { ErrorState,LoadingState } from '../components/PageState'
import { AppCard,InlineNotice,PageShell } from '../components/ProductUI'
import { getToeicPart3Result,getToeicPart3Review } from '../services/native'
import type { ToeicBreakdown,ToeicPart3Result,ToeicPart3ReviewSet } from '../types'
export function ToeicPart3ResultsPage(){const{sessionId=''}=useParams();const nav=useNavigate();const[result,setResult]=useState<ToeicPart3Result|null>(null);const[review,setReview]=useState<ToeicPart3ReviewSet[]|null>(null);const[error,setError]=useState<string|null>(null);const load=()=>{setError(null);void getToeicPart3Result(sessionId).then(setResult).catch(x=>setError(msg(x)))};useEffect(load,[sessionId]);const open=async(m:boolean)=>{try{setReview(await getToeicPart3Review(sessionId,m))}catch(x){setError(msg(x))}};if(error&&!result)return <ErrorState message={error} onRetry={load}/>;if(!result)return <LoadingState label="Calculating deterministic Part 3 results…"/>;return <PageShell width="wide"><section className="toeic-result-hero"><div><p className="eyebrow">Part 3 complete</p><h1>{result.correct} / 39</h1><strong>{result.accuracy}% accuracy</strong></div><div className="toeic-score-ring" style={{'--score':`${result.accuracy*3.6}deg`} as React.CSSProperties}><span>{result.accuracy}%</span></div></section><InlineNotice tone="info"><BarChart3/>{result.scoreMessage}</InlineNotice><div className="toeic-results-grid"><Panel title="Question type" rows={result.questionTypeBreakdown}/><Panel title="Difficulty" rows={result.difficultyBreakdown}/><Panel title="Listening skill" rows={result.skillBreakdown}/></div><div className="toeic-result-actions"><button className="button-primary" onClick={()=>void open(true)}><RotateCcw/>Review mistakes</button><button className="button-secondary" onClick={()=>void open(false)}><BookOpen/>Review all</button><button className="button-ghost" onClick={()=>nav('/toeic')}><Headphones/>Back to TOEIC</button></div>{review&&<section className="toeic-review-section">{review.length===0?<AppCard><CheckCircle2/>No mistakes in this form.</AppCard>:review.map(set=><AppCard key={set.setNumber}><p className="eyebrow">Conversation {set.setNumber} · {pretty(set.scenario)}</p><div className="toeic-transcript">{set.feedback.transcript.map((t,i)=><p key={i}><b>Speaker {t.speaker}:</b> {t.text}</p>)}</div>{set.feedback.questions.map((q,i)=><div key={q.questionId}><h3>Question {i+1}: {q.isCorrect?'Correct':`${q.selectedChoice} → ${q.correctAnswer}`}</h3><p>{q.correctExplanation}</p><p><strong>Evidence:</strong> “{q.evidence}”</p></div>)}</AppCard>)}</section>}</PageShell>}
function Panel({title,rows}:{title:string;rows:ToeicBreakdown[]}){return <AppCard><h2>{title}</h2>{rows.map(x=><div className="toeic-result-bar" key={x.label}><div><span>{pretty(x.label)}</span><b>{x.correct}/{x.total}</b></div><div><i style={{width:`${x.total?x.correct/x.total*100:0}%`}}/></div></div>)}</AppCard>}function pretty(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function msg(x:unknown){return x instanceof Error?x.message:String(x)}
