import { Activity, CheckCircle2, Clipboard, RefreshCw, TriangleAlert, XCircle } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { exportDiagnosticReport, getSystemDiagnostics, listRecentSystemEvents } from '../services/native'
import type { DiagnosticComponent, SystemDiagnostics, SystemEvent } from '../types'
import { ErrorState, LoadingState } from '../components/PageState'
import { PageHeader, PageShell } from '../components/ProductUI'

const COMPONENTS: Array<[keyof Pick<SystemDiagnostics,'database'|'ollama'|'whisper'|'piper'|'voiceBridge'|'voiceStreaming'|'pronunciation'|'settings'>,string]>=[['database','Database'],['ollama','Ollama'],['whisper','Whisper'],['piper','Piper'],['voiceBridge','Voice Bridge'],['voiceStreaming','Voice Streaming'],['pronunciation','Pronunciation'],['settings','Settings']]

export function DiagnosticsPage(){
  const [report,setReport]=useState<SystemDiagnostics|null>(null);const[events,setEvents]=useState<SystemEvent[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);const[copied,setCopied]=useState(false)
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const[next,history]=await Promise.all([getSystemDiagnostics(),listRecentSystemEvents(20)]);setReport(next);setEvents(history)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  async function copyReport(){try{const text=await exportDiagnosticReport();await navigator.clipboard.writeText(text);setCopied(true);window.setTimeout(()=>setCopied(false),2000)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}}
  return <PageShell width="wide"><PageHeader eyebrow="Local reliability" title="System Diagnostics" description="Read-only checks for your database and local AI components. Diagnostics never record audio or generate a teacher response." />
    <div className="mb-5 flex flex-wrap gap-3"><button type="button" aria-busy={loading} disabled={loading} onClick={()=>void load()} className="button-primary"><RefreshCw size={16}/>Run Diagnostics Again</button><button type="button" disabled={!report} onClick={()=>void copyReport()} className="button-secondary"><Clipboard size={16}/>{copied?'Copied':'Copy Diagnostic Report'}</button></div>
    {loading&&<LoadingState label="Checking local components…"/>}{error&&<ErrorState message={error} onRetry={load}/>} {report&&<><section className="glass rounded-[28px] p-5 md:p-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="eyebrow">Overall status</p><h2 className="section-title text-xl">{report.overallStatus}</h2></div><div className="grid min-w-0 grid-cols-1 gap-2 text-center text-xs sm:grid-cols-3"><Readiness label="Database" ready={report.databaseReady}/><Readiness label="Conversation" ready={report.conversationReady}/><Readiness label="Pronunciation" ready={report.pronunciationReady}/></div></div></section><section className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{COMPONENTS.map(([key,label])=><ComponentCard key={key} label={label} value={report[key]}/>)}</section></>}
    <section className="glass mt-5 rounded-[28px] p-5 md:p-7"><div className="flex items-center gap-2"><Activity size={18} className="text-[var(--accent)]"/><h2 className="section-title">Recent technical events</h2></div>{events.length===0?<p className="muted mb-0 mt-3 text-sm">No warnings, errors, or recovery events are recorded. The empty list is a healthy state.</p>:<ul className="mb-0 mt-4 space-y-2 pl-5 text-sm">{events.map(event=><li key={event.id} className="break-words"><span className="font-medium">{event.eventCode}</span><span className="muted"> · {event.component} · {event.occurredAt}</span></li>)}</ul>}</section>
    <p className="muted mt-4 text-xs">Report version {report?.reportVersion??1}. Export stays on this computer and excludes transcripts, profile content, vocabulary, pronunciation targets, prompts and audio.</p>
  </PageShell>
}
function Readiness({label,ready}:{label:string;ready:boolean}){return <div className={`rounded-xl border px-3 py-2 ${ready?'border-emerald-300/20 bg-emerald-300/[.06] text-emerald-200':'border-amber-300/20 bg-amber-300/[.06] text-amber-100'}`}>{label}<span className="block font-semibold">{ready?'Ready':'Attention'}</span></div>}
function ComponentCard({label,value}:{label:string;value:DiagnosticComponent}){const Icon=value.status==='healthy'?CheckCircle2:value.status==='warning'?TriangleAlert:XCircle;return <article className="glass rounded-[24px] p-5"><div className="flex items-start gap-3"><Icon aria-hidden="true" size={20} className={value.status==='healthy'?'text-emerald-300':value.status==='warning'?'text-amber-300':'text-red-300'}/><div className="min-w-0"><h2 className="m-0 text-base">{label}</h2><p className="muted mb-0 mt-2 text-sm">{value.message}</p>{value.version&&<p className="muted mb-0 mt-2 text-xs">Version: {value.version}</p>}{value.technicalCode&&<p className="mb-0 mt-2 text-xs text-amber-200">{value.technicalCode}</p>}</div></div><details className="mt-4"><summary className="cursor-pointer text-xs text-[var(--accent)]">Advanced details</summary><pre className="mt-3 max-h-52 overflow-auto whitespace-pre-wrap break-all rounded-xl bg-black/20 p-3 text-xs">{JSON.stringify(value.advancedDetails,null,2)}</pre></details></article>}
