import { AlertTriangle, CheckCircle2, Play, RotateCcw, XCircle } from 'lucide-react'
import { useCallback,useEffect,useRef,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { ErrorState,LoadingState } from '../components/PageState'
import { AppCard,InlineNotice,PageShell } from '../components/ProductUI'
import { advanceToeicPart3Session,cancelToeicPart3Audio,completeToeicPart3Audio,getToeicPart3Session,prepareToeicPart3Audio,submitToeicPart3Answer } from '../services/native'
import type { ToeicPart3Audio,ToeicPart3Feedback,ToeicPart3Graphic,ToeicPart3Session } from '../types'
export function ToeicPart3SessionPage(){const{sessionId=''}=useParams();const nav=useNavigate();const[s,setS]=useState<ToeicPart3Session|null>(null);const[error,setError]=useState<string|null>(null);const[playing,setPlaying]=useState(false);const[busy,setBusy]=useState(false);const active=useRef<{audio:HTMLAudioElement;data:ToeicPart3Audio}|null>(null);const load=useCallback(()=>{setError(null);void getToeicPart3Session(sessionId).then(x=>{if(x.status==='completed')nav(`/toeic/part3/results/${sessionId}`,{replace:true});else setS(x)}).catch(x=>setError(msg(x)))},[nav,sessionId]);useEffect(load,[load]);useEffect(()=>()=>{if(active.current){active.current.audio.pause();void cancelToeicPart3Audio(active.current.data)}},[]);if(error&&!s)return <ErrorState message={error} onRetry={load}/>;if(!s)return <LoadingState label="Restoring TOEIC Part 3…"/>;const set=s.currentSet;if(!set)return <ErrorState message="The current conversation could not be restored." onRetry={load}/>;
const play=async()=>{setBusy(true);setError(null);let pid:string|null=null;setPlaying(true);try{for(let turn=0;;turn++){const data=await prepareToeicPart3Audio(s.sessionId,turn,pid);pid=data.presentationId;await new Promise<void>((resolve,reject)=>{const audio=new Audio(`data:${data.mimeType};base64,${data.audioBase64}`);active.current={audio,data};audio.onended=()=>{void completeToeicPart3Audio(data,s.sessionId).then(updated=>{setS(updated);active.current=null;resolve()}).catch(reject)};audio.onerror=()=>reject(new Error('The local conversation audio could not be played.'));void audio.play().catch(reject)});if(turn+1===data.turnCount)break}}catch(x){if(active.current)void cancelToeicPart3Audio(active.current.data);setError(msg(x))}finally{active.current=null;setPlaying(false);setBusy(false)}};
const answer=async(q:string,c:string)=>{setBusy(true);try{setS(await submitToeicPart3Answer(s.sessionId,q,c))}catch(x){setError(msg(x))}finally{setBusy(false)}};const next=async()=>{setBusy(true);try{const x=await advanceToeicPart3Session(s.sessionId);if(x.status==='completed')nav(`/toeic/part3/results/${s.sessionId}`);else setS(x)}catch(x){setError(msg(x))}finally{setBusy(false)}};
return <PageShell width="wide"><div className="toeic-session-head"><button className="button-ghost" onClick={()=>nav('/toeic')}>← Save & exit</button><div><strong>Part 3 — Conversations</strong><span>Conversation {set.setNumber} of 13 · {s.answeredCount}/39 answered</span></div><span className="toeic-untimed">Untimed</span></div><div className="toeic-progress"><span style={{width:`${set.setNumber/13*100}%`}}/></div><InlineNotice tone="info">You can pause freely between conversations. Once audio starts, try to complete all three questions before leaving.</InlineNotice>{error&&<InlineNotice tone="warning" live>{error}</InlineNotice>}{set.initialAudioInterrupted&&!set.initialAudioCompleted&&<InlineNotice tone="info"><AlertTriangle/>Playback was interrupted. It can restart from the beginning without penalty.</InlineNotice>}<div className="toeic-part3-layout"><section><AppCard><p className="eyebrow">Conversation {set.setNumber}</p><h1>Read the questions, then play the conversation once.</h1>{set.graphic&&<Graphic graphic={set.graphic}/>}<button className="toeic-audio-button" disabled={busy||playing||(!s.feedback&&set.initialAudioCompleted)} onClick={()=>void play()}>{s.feedback?<RotateCcw/>:<Play fill="currentColor"/>}{playing?'Playing conversation…':s.feedback?'Listen again':set.initialAudioCompleted?'Conversation played':'Play conversation once'}</button></AppCard>{set.questions.map((q,i)=><AppCard key={q.questionId} className="mt-4"><p className="eyebrow">Question {i+1}</p><h2>{q.text}</h2><div className="toeic-part3-choices">{q.choices.map(c=><button className={q.selectedChoice===c.choice?'selected':''} disabled={busy||playing||!set.initialAudioCompleted||q.answered} onClick={()=>void answer(q.questionId,c.choice)} key={c.choice}><b>{c.choice}</b><span>{c.text}</span>{q.selectedChoice===c.choice&&<small>Answer recorded</small>}</button>)}</div></AppCard>)}</section>{s.feedback&&<Feedback feedback={s.feedback} onNext={()=>void next()} busy={busy||playing} final={set.setNumber===13}/>}</div></PageShell>}
function Graphic({graphic:g}:{graphic:ToeicPart3Graphic}){return <figure className="toeic-part3-graphic"><figcaption>{g.title}</figcaption><table><thead><tr>{g.columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{g.rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></figure>}
function Feedback({feedback:f,onNext,busy,final}:{feedback:ToeicPart3Feedback;onNext:()=>void;busy:boolean;final:boolean}){const[transcript,setTranscript]=useState(false);return <aside><AppCard><p className="eyebrow">Conversation results</p>{f.questions.map((q,i)=><div className={`toeic-part3-feedback ${q.isCorrect?'correct':'incorrect'}`} key={q.questionId}>{q.isCorrect?<CheckCircle2/>:<XCircle/>}<div><h3>Question {i+1}: {q.isCorrect?'Correct':'Incorrect'}</h3>{!q.isCorrect&&<><p>Your answer: {q.selectedChoice} · Correct: {q.correctAnswer}</p><p><strong>Why:</strong> {q.correctExplanation}</p><p><strong>Evidence:</strong> “{q.evidence}”</p><p><strong>Why {q.selectedChoice} is incorrect:</strong> {q.selectedExplanation}</p><p><strong>Notice next time:</strong> {q.noticeNextTime}</p></>}</div></div>)}<button className="button-secondary" onClick={()=>setTranscript(x=>!x)}>{transcript?'Hide':'Show'} conversation transcript</button>{transcript&&<div className="toeic-transcript">{f.transcript.map((t,i)=><p key={i}><b>Speaker {t.speaker}:</b> {t.text}</p>)}</div>}<button className="button-primary toeic-next" disabled={busy} onClick={onNext}>{final?'Complete Part 3':'Continue'} →</button><button className="button-ghost" onClick={()=>location.assign('/toeic')}>Pause & Exit</button></AppCard></aside>}
function msg(x:unknown){return x instanceof Error?x.message:String(x)}
