// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { PracticeSessionPage } from './PracticeSessionPage'

const native=vi.hoisted(()=>({getPracticeSession:vi.fn(),recordPracticeTime:vi.fn(),completePracticeSession:vi.fn(),completePracticeItem:vi.fn(),preparePracticeAudio:vi.fn(),analyzePronunciation:vi.fn(),transcribeAudio:vi.fn(),cancelGuidedLessonPronunciation:vi.fn()}))
vi.mock('../services/native',()=>native)
beforeEach(()=>native.getPracticeSession.mockResolvedValue({id:'done',mode:'daily',status:'completed',schemaVersion:1,selectionVersion:1,items:[{kind:'vocabulary',itemId:'v1',term:'hello',meaning:'a greeting',example:'Hello there',status:'learning',sourceLabel:'Your vocabulary'}],completedItemIds:['v1'],activeSeconds:30,xpAwarded:20,startedAt:'2026-01-01',completedAt:'2026-01-01'}))
describe('PracticeSessionPage',()=>{
  it('renders a saved completion without throwing or mutating it again',async()=>{render(<MemoryRouter initialEntries={['/practice/session/done']}><Routes><Route path="/practice/session/:sessionId" element={<PracticeSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText(/practice was saved/i)).toBeInTheDocument();expect(screen.getByText(/20 XP awarded once/)).toBeInTheDocument();expect(native.completePracticeSession).not.toHaveBeenCalled()})
  it('makes the dictation typing area large and explicit',async()=>{native.getPracticeSession.mockResolvedValue({id:'dictation',mode:'dictation',status:'in_progress',schemaVersion:1,selectionVersion:1,items:[{kind:'dictation',itemId:'d1',targetText:'Hidden answer',sourceLabel:'A lesson'}],completedItemIds:[],activeSeconds:0,xpAwarded:0,startedAt:'2026-01-01',completedAt:null});render(<MemoryRouter initialEntries={['/practice/session/dictation']}><Routes><Route path="/practice/session/:sessionId" element={<PracticeSessionPage/>}/></Routes></MemoryRouter>);const field=await screen.findByRole('textbox',{name:'What did you hear?'});expect(field).toHaveAttribute('rows','5');expect(field).toHaveAttribute('placeholder','Click here and type exactly what you heard…');expect(screen.getByText('Type your answer here')).toBeInTheDocument();expect(screen.getByText(/large box below/i)).toBeInTheDocument()})
  it('uses the same prominent typing area for mistake repair',async()=>{native.getPracticeSession.mockResolvedValue({id:'repair',mode:'mistake_repair',status:'in_progress',schemaVersion:1,selectionVersion:1,items:[{kind:'mistake_repair',itemId:'m1',mistakeId:'mistake-1',original:'I go yesterday.',corrected:'I went yesterday.',explanation:'Use the past tense.',sourceLabel:'Recurring mistake'}],completedItemIds:[],activeSeconds:0,xpAwarded:0,startedAt:'2026-01-01',completedAt:null});render(<MemoryRouter initialEntries={['/practice/session/repair']}><Routes><Route path="/practice/session/:sessionId" element={<PracticeSessionPage/>}/></Routes></MemoryRouter>);fireEvent.click(await screen.findByRole('button',{name:'Show the repair'}));const field=screen.getByRole('textbox',{name:'Rebuild the phrase'});expect(field).toHaveAttribute('placeholder','Click here and type the corrected phrase…');expect(screen.getByText(/entire corrected phrase/i)).toBeInTheDocument()})
})
