// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ToeicPage } from './ToeicPage'
import { ToeicSessionPage } from './ToeicSessionPage'

const native=vi.hoisted(()=>({getToeicOverview:vi.fn(),startToeicSession:vi.fn(),getToeicSession:vi.fn(),submitToeicAnswer:vi.fn(),advanceToeicSession:vi.fn(),cancelToeicAudio:vi.fn(),completeToeicAudio:vi.fn(),prepareToeicAudio:vi.fn(),recordToeicActiveTime:vi.fn()}))
vi.mock('../services/native',()=>native)
const question={itemId:'toeic-l-p1-0001',itemVersion:1,questionNumber:1,totalQuestions:6,imageBase64:'AA==',imageMimeType:'image/png',choices:['A','B','C','D'],initialAudioCompleted:true,initialAudioInterrupted:false}
const session={sessionId:'session-1',formId:'toeic-part1-form-a',formVersion:1,formTitle:'Part 1 Form A',status:'in_progress',untimed:true,currentQuestionIndex:0,answeredCount:0,currentQuestion:question,feedback:null,createdAt:'2026-08-31T12:00:00Z',updatedAt:'2026-08-31T12:00:00Z'}
beforeEach(()=>{vi.clearAllMocks();native.getToeicOverview.mockResolvedValue({bankId:'bank',untimed:true,parts:[{part:'part1_photograph',title:'Photographs',questionCount:6,runtimeAvailable:true},{part:'part2_question_response',title:'Question–Response',questionCount:25,runtimeAvailable:false}],forms:[{formId:'toeic-part1-form-a',formVersion:1,title:'Part 1 Form A',questionCount:6,activeSessionId:null}],activeSessions:[],recentHistory:[],disclaimer:'Independent preparation; not an official ETS product.'});native.getToeicSession.mockResolvedValue(session);native.submitToeicAnswer.mockResolvedValue({...session,answeredCount:1,feedback:{selectedChoice:'A',isCorrect:false,correctAnswer:'B',statements:[{choice:'A',text:'Wrong statement.'},{choice:'B',text:'Correct statement.'},{choice:'C',text:'Another statement.'},{choice:'D',text:'Final statement.'}],correctExplanation:'The photograph clearly supports statement B.',selectedExplanation:'The action in statement A is not shown.',languageFocus:['Present progressive'],usefulVocabulary:['filing cabinet'],answeredAt:'2026-08-31T12:01:00Z'}})})
describe('TOEIC Phase 1 UI',()=>{
  it('shows only Part 1 as available and identifies the simulation as untimed',async()=>{render(<MemoryRouter><ToeicPage/></MemoryRouter>);expect(await screen.findByText('Untimed by design')).toBeInTheDocument();expect(screen.getByText('Part 1 — Photographs')).toBeInTheDocument();expect(screen.getByText('Not yet available')).toBeInTheDocument();expect(screen.getByText(/not an official ETS product/i)).toBeInTheDocument()})
  it('never renders statement transcripts before the first answer and reveals authored feedback after it',async()=>{render(<MemoryRouter initialEntries={['/toeic/session/session-1']}><Routes><Route path="/toeic/session/:sessionId" element={<ToeicSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole('button',{name:'Choose answer A'})).toBeInTheDocument();expect(screen.queryByText('Correct statement.')).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Choose answer A'}));await waitFor(()=>expect(native.submitToeicAnswer).toHaveBeenCalledWith('session-1','toeic-l-p1-0001',1,'A'));expect(await screen.findByText('Incorrect')).toBeInTheDocument();expect(screen.getByText('“Correct statement.”')).toBeInTheDocument();expect(screen.getByText(/first answer is locked/i)).toBeInTheDocument()})
})
