// @vitest-environment jsdom
import '@testing-library/jest-dom/vitest'
import { cleanup, fireEvent, render, screen } from '@testing-library/react'
import { MemoryRouter, Route, Routes } from 'react-router-dom'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import * as native from '../services/native'
import type { GuidedActiveContent, GuidedExerciseAttempt, GuidedExerciseItem, GuidedLessonSession } from '../types'
import { GuidedLessonsPage } from './GuidedLessonsPage'
import { GuidedLessonSessionPage } from './GuidedLessonSessionPage'

vi.mock('../services/native',()=>({
  getGuidedLessonOverview:vi.fn(),listGuidedLessons:vi.fn(),listRecentGuidedLessonSessions:vi.fn(),
  getGuidedLessonSession:vi.fn(),completeGuidedLessonStage:vi.fn(),skipGuidedLessonStage:vi.fn(),abandonGuidedLesson:vi.fn(),
  prepareGuidedLessonAudio:vi.fn(),completeGuidedLessonAudio:vi.fn(),cancelGuidedLessonAudio:vi.fn(),submitGuidedLessonPronunciation:vi.fn(),selectGuidedLessonPronunciationAttempt:vi.fn(),
  cancelGuidedLessonPronunciation:vi.fn(),
  submitGuidedLessonExerciseAttempt:vi.fn(),selectGuidedLessonExerciseAttempt:vi.fn(),
  getGuidedLessonAnalysis:vi.fn(),analyzeGuidedLesson:vi.fn(),retryGuidedLessonConversationAnalysis:vi.fn(),finalizeGuidedLessonAnalysis:vi.fn(),
}))

const base:GuidedLessonSession={id:'session-1',lessonId:'everyday-greetings-a1',contentVersion:1,title:'Everyday Greetings',cefrBand:'A1',status:'in_progress',currentStageIndex:0,stageCount:2,progressPercent:0,startedAt:'2026-08-24',completedAt:null,abandonedAt:null,stages:[{stageId:'theory',sequenceIndex:0,stageType:'theory',title:'Theory',required:true,status:'active',attemptCount:0},{stageId:'words',sequenceIndex:1,stageType:'visual_vocabulary',title:'Words',required:true,status:'pending',attemptCount:0}],activeStage:{stageId:'theory',sequenceIndex:0,stageType:'theory',title:'Theory',instructions:'Read this.',required:true,content:{kind:'theory',blocks:[{type:'paragraph',text:'Greetings open a conversation.'},{type:'example',english:'Hello!',explanation:'A neutral greeting.'}]}}}
const exerciseSession=(item:GuidedExerciseItem,summary:Extract<GuidedActiveContent,{kind:'exercise'}>['stage']['summary']=null):GuidedLessonSession=>({...base,stageCount:1,stages:[{stageId:'practice',sequenceIndex:0,stageType:'exercise',title:'Practice',required:true,status:'active',attemptCount:0}],activeStage:{stageId:'practice',sequenceIndex:0,stageType:'exercise',title:'Practice',instructions:'Complete the exercises.',required:true,content:{kind:'exercise',stage:{engineVersion:1,stageSchemaVersion:1,attemptResultVersion:1,normalizationVersion:1,currentExerciseIndex:summary?1:0,items:[item],summary}}}})
const attempt:GuidedExerciseAttempt={attemptId:'attempt-1',attemptIndex:1,correct:false,selected:false,feedback:'Review the answer.',explanation:'A package explanation.',expectedAnswer:{kind:'single_choice',option:{optionId:'b',text:'The private expected option'}},normalizationVersion:1,submittedAt:'now',selectedAt:null}

afterEach(cleanup)
beforeEach(()=>{vi.resetAllMocks();vi.mocked(native.getGuidedLessonOverview).mockResolvedValue({publishedLessonCount:0,activeSession:null,capabilities:[]});vi.mocked(native.listGuidedLessons).mockResolvedValue([]);vi.mocked(native.listRecentGuidedLessonSessions).mockResolvedValue([])})

describe('Guided Lessons UI foundation',()=>{
  it('shows the exact production empty state without exposing roadmap content',async()=>{render(<MemoryRouter><GuidedLessonsPage/></MemoryRouter>);expect(await screen.findByRole('heading',{name:'No guided lessons are installed yet.'})).toBeInTheDocument();expect(screen.queryByText(/coming soon/i)).not.toBeInTheDocument()})
  it('renders typed theory and advances with one backend action',async()=>{vi.mocked(native.getGuidedLessonSession).mockResolvedValue(base);const vocabulary={...base,currentStageIndex:1,progressPercent:50,stages:[{...base.stages[0],status:'completed' as const,attemptCount:1},{...base.stages[1],status:'active' as const}],activeStage:{stageId:'words',sequenceIndex:1,stageType:'visual_vocabulary' as const,title:'Words',instructions:'Review.',required:true,content:{kind:'visual_vocabulary' as const,items:[{itemId:'hello',term:'Hello',meaning:'A greeting.',example:'Hello, Ana.',imageAssetId:null}]}}};vi.mocked(native.completeGuidedLessonStage).mockResolvedValue(vocabulary);render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText('Greetings open a conversation.')).toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'Continue'}));expect(await screen.findByRole('heading',{name:'Hello'})).toBeInTheDocument();expect(native.completeGuidedLessonStage).toHaveBeenCalledWith('session-1','theory')})
  it('renders completion for a legacy package without inventing analysis',async()=>{vi.mocked(native.getGuidedLessonSession).mockResolvedValue({...base,status:'completed',progressPercent:100,activeStage:null,completedAt:'2026-08-24'});render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText(/did not include a review stage/i)).toBeInTheDocument()})
  it('shows a friendly state for an unknown session',async()=>{vi.mocked(native.getGuidedLessonSession).mockResolvedValue(null);render(<MemoryRouter initialEntries={['/guided-lessons/session/missing']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole('heading',{name:'Guided lesson session not found'})).toBeInTheDocument()})
  it('keeps Listening text hidden before a completed first playback',async()=>{vi.mocked(native.getGuidedLessonSession).mockResolvedValue({...base,stageCount:1,activeStage:{stageId:'listen',sequenceIndex:0,stageType:'listening',title:'Listen',instructions:'Listen fully.',required:true,content:{kind:'listening',revealTextAfterFirstPlay:true,segments:[{segmentId:'one',text:'Hello from the lesson.',hasBundledAudio:false,completedPlaybackCount:0}]}}});render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText('Text appears after the first complete playback.')).toBeInTheDocument();expect(screen.queryByText('Hello from the lesson.')).not.toBeInTheDocument();expect(screen.getByRole('button',{name:'Play'})).toBeEnabled()})
  it('allows Speaking Check recording without exposing reference playback',async()=>{vi.mocked(native.getGuidedLessonSession).mockResolvedValue({...base,stageCount:1,activeStage:{stageId:'speak',sequenceIndex:0,stageType:'speaking_check',title:'Speaking Check',instructions:'Speak now.',required:true,content:{kind:'speaking_check',targets:[{targetId:'one',instruction:'Say it naturally.',targetText:'Nice to meet you.',hint:null,selectedAttemptId:null,attempts:[]}]}}});render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole('button',{name:'Record'})).toBeEnabled();expect(screen.queryByRole('button',{name:/reference/i})).not.toBeInTheDocument()})
  it('keeps the Single Choice answer private until submit, then offers retry or continue',async()=>{const item:GuidedExerciseItem={exerciseId:'choice',exerciseType:'single_choice',prompt:'Choose one.',instructions:null,hint:'A safe hint.',payload:{options:[{optionId:'a',text:'Public A'},{optionId:'b',text:'Public B'}]},attempts:[],selectedAttemptId:null};const initial=exerciseSession(item);const graded=exerciseSession({...item,attempts:[attempt]});vi.mocked(native.getGuidedLessonSession).mockResolvedValue(initial);vi.mocked(native.submitGuidedLessonExerciseAttempt).mockResolvedValue(graded);render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByRole('radio',{name:'Public A'})).toBeInTheDocument();expect(screen.queryByText('The private expected option')).not.toBeInTheDocument();const submit=screen.getByRole('button',{name:'Submit answer'});expect(submit).toBeDisabled();fireEvent.click(screen.getByRole('radio',{name:'Public A'}));fireEvent.click(submit);expect(await screen.findByText('The private expected option')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Try Again'})).toBeEnabled();expect(screen.getByRole('button',{name:'Continue'})).toBeEnabled()})
  it('renders Multiple Select, Fill Blank, Word Order, Matching and Short Exact with keyboard-safe controls',async()=>{const items:GuidedExerciseItem[]=[{exerciseId:'multi',exerciseType:'multiple_select',prompt:'Select.',instructions:null,hint:null,payload:{options:[{optionId:'a',text:'One'},{optionId:'b',text:'Two'}]},attempts:[],selectedAttemptId:null},{exerciseId:'blank',exerciseType:'fill_blank',prompt:'Complete.',instructions:null,hint:null,payload:{prefix:'A ',suffix:'.'},attempts:[],selectedAttemptId:null},{exerciseId:'order',exerciseType:'word_order',prompt:'Order.',instructions:null,hint:null,payload:{tokens:[{tokenId:'one',text:'is'},{tokenId:'two',text:'is'}]},attempts:[],selectedAttemptId:null},{exerciseId:'matching',exerciseType:'matching',prompt:'Match.',instructions:null,hint:null,payload:{leftItems:[{itemId:'l1',text:'coffee'},{itemId:'l2',text:'water'}],rightItems:[{itemId:'r1',text:'café'},{itemId:'r2',text:'água'}]},attempts:[],selectedAttemptId:null},{exerciseId:'short',exerciseType:'short_answer_exact',prompt:'Opposite?',instructions:null,hint:null,payload:{normalizationProfile:'english_basic_v1'},attempts:[],selectedAttemptId:null}];for(const item of items){cleanup();vi.mocked(native.getGuidedLessonSession).mockResolvedValue(exerciseSession(item));render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);await screen.findByRole('heading',{name:item.prompt});if(item.exerciseType==='multiple_select')expect(screen.getAllByRole('checkbox')).toHaveLength(2);if(item.exerciseType==='fill_blank')expect(screen.getByRole('textbox',{name:'Fill in the blank'})).toBeInTheDocument();if(item.exerciseType==='word_order'){expect(screen.getAllByRole('button',{name:'is'})).toHaveLength(2);fireEvent.click(screen.getAllByRole('button',{name:'is'})[0]);expect(screen.getByRole('button',{name:'Remove is'})).toBeInTheDocument()}if(item.exerciseType==='matching')expect(screen.getAllByRole('combobox')).toHaveLength(2);if(item.exerciseType==='short_answer_exact')expect(screen.getByRole('textbox',{name:'Your short answer'})).toBeInTheDocument()}})
  it('allows a zero-accuracy summary to complete without pass or fail language',async()=>{const item:GuidedExerciseItem={exerciseId:'choice',exerciseType:'single_choice',prompt:'Choose.',instructions:null,hint:null,payload:{options:[{optionId:'a',text:'A'},{optionId:'b',text:'B'}]},attempts:[{...attempt,selected:true}],selectedAttemptId:'attempt-1'};vi.mocked(native.getGuidedLessonSession).mockResolvedValue(exerciseSession(item,{exerciseCount:1,selectedCorrectCount:0,selectedIncorrectCount:1,totalAttemptCount:3,accuracyPercent:0}));render(<MemoryRouter initialEntries={['/guided-lessons/session/session-1']}><Routes><Route path="/guided-lessons/session/:sessionId" element={<GuidedLessonSessionPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText('0% Exercise Accuracy')).toBeInTheDocument();expect(screen.getByRole('button',{name:'Complete Exercise Stage'})).toBeEnabled();expect(screen.queryByText(/^failed$/i)).not.toBeInTheDocument();expect(screen.queryByText(/^passed$/i)).not.toBeInTheDocument()})
})
