import { ArrowLeft, Check, Headphones, Mic2, Square, Volume2 } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { AppCard, InlineNotice, PageHeader, PageShell, ProgressBar, StatusBadge } from '../components/ProductUI'
import { useGuidedLessonRecorder } from '../hooks/useGuidedLessonRecorder'
import { analyzePronunciation, completePracticeItem, completePracticeSession, getPracticeSession, preparePracticeAudio, recordPracticeTime, transcribeAudio } from '../services/native'
import type { PracticeItem, PracticeItemResult, PracticeSession, PronunciationAttempt } from '../types'
import { wordFeedback } from '../utils/pronunciationFeedback'

export function PracticeSessionPage() {
  const { sessionId = '' } = useParams(); const navigate = useNavigate()
  const [session, setSession] = useState<PracticeSession | null>(null)
  const [error, setError] = useState<string | null>(null)
  const [busy, setBusy] = useState(false)
  const load = useCallback(() => { setError(null); void getPracticeSession(sessionId).then(setSession).catch(value => setError(message(value))) }, [sessionId])
  useEffect(load, [load])
  const activeSessionId = session?.status === 'in_progress' ? session.id : null
  useEffect(() => { if (!activeSessionId) return; const timer = window.setInterval(() => { void recordPracticeTime(activeSessionId, crypto.randomUUID(), 15) }, 15_000); return () => window.clearInterval(timer) }, [activeSessionId])
  const completed = new Set(session?.completedItemIds ?? [])
  const index = session?.items.findIndex(item => !completed.has(item.itemId)) ?? -1
  const item = index >= 0 ? session?.items[index] : undefined
  const finish = async () => { if (!session) return; setBusy(true); try { setSession(await completePracticeSession(session.id)) } catch (value) { setError(message(value)) } finally { setBusy(false) } }
  if (error && !session) return <ErrorState message={error} onRetry={load} />
  if (!session) return <LoadingState label="Opening your practice snapshot…" />
  if (session.status === 'completed') return <PageShell width="narrow"><PageHeader eyebrow="Practice complete" title="Nice work—your practice was saved." description={`${session.items.length} items completed · ${session.xpAwarded} XP awarded once`} /><AppCard className="practice-complete-card"><Check size={38} /><p>Your results, active practice time, and item provenance remain on this device.</p><div className="flex flex-wrap justify-center gap-3"><button className="button-primary" onClick={() => navigate('/practice')}>Choose another practice</button><Link className="button-secondary" to="/">Back to Home</Link></div></AppCard></PageShell>
  return <PageShell width="standard">
    <PageHeader eyebrow={label(session.mode)} title={`${label(session.mode)} session`} description="Work at your own pace. Accuracy never changes the XP reward." back={<Link to="/practice" className="text-link"><ArrowLeft size={16} /> Back to Practice</Link>} actions={<StatusBadge tone="info">Offline</StatusBadge>} />
    <AppCard><div className="flex items-center justify-between gap-4"><strong>{completed.size} of {session.items.length} items</strong><span className="section-description">{Math.floor(session.activeSeconds / 60)} min active</span></div><div className="mt-3"><ProgressBar value={session.items.length ? completed.size * 100 / session.items.length : 0} label="Practice progress" /></div></AppCard>
    {error && <div className="mt-4"><InlineNotice tone="error" live>{error}</InlineNotice></div>}
    {item ? <PracticeItemCard key={item.itemId} item={item} sessionId={session.id} onDone={(result) => { setSession(result.session); setError(null) }} onError={setError} /> : <AppCard className="mt-4 text-center"><h2 className="section-title">All items complete</h2><p className="section-description mt-2">Finish once to persist this session and its fixed practice reward.</p><button disabled={busy} className="button-primary mt-5" onClick={() => void finish()}><Check size={17} />{busy ? 'Saving…' : 'Complete practice'}</button></AppCard>}
  </PageShell>
}

function PracticeItemCard({ item, sessionId, onDone, onError }: { item: PracticeItem; sessionId: string; onDone: (result: PracticeItemResult) => void; onError: (value: string | null) => void }) {
  const [revealed, setRevealed] = useState(false); const [response, setResponse] = useState(''); const [result, setResult] = useState<PracticeItemResult | null>(null); const [pronunciation, setPronunciation] = useState<PronunciationAttempt | null>(null); const [listened, setListened] = useState(false); const [busy, setBusy] = useState(false)
  const capture = useCallback(async (audioBase64: string) => {
    if (item.kind === 'shadowing') setPronunciation(await analyzePronunciation(item.targetText, audioBase64, 'custom', `practice:${item.itemId}`))
    else if (item.kind === 'mistake_repair') setPronunciation(await analyzePronunciation(item.corrected, audioBase64, 'custom', `practice:${item.itemId}`))
    else if (item.kind === 'speaking_recall') setResponse((await transcribeAudio(audioBase64)).text)
  }, [item])
  const recorder = useGuidedLessonRecorder(capture)
  const play = async () => { setBusy(true); onError(null); try { const audio = await preparePracticeAudio(sessionId, item.itemId); const player = new Audio(`data:${audio.mimeType};base64,${audio.audioBase64}`); await player.play(); await new Promise<void>((resolve, reject) => { player.onended = () => resolve(); player.onerror = () => reject(new Error('Audio playback failed.')) }); setListened(true) } catch (value) { onError(message(value)) } finally { setBusy(false) } }
  const submit = async (selfAssessment?: string) => { setBusy(true); onError(null); try { const value = await completePracticeItem({ sessionId, itemId: item.itemId, response: response || undefined, selfAssessment }); setResult(value); setRevealed(true) } catch (value) { onError(message(value)) } finally { setBusy(false) } }
  const next = () => { if (result) onDone(result) }
  const title = item.kind === 'vocabulary' ? 'Recall the word' : item.kind === 'dictation' ? 'Type what you hear' : item.kind === 'shadowing' ? 'Listen, then shadow' : item.kind === 'mistake_repair' ? 'Repair this pattern' : 'Recall the expression'
  return <AppCard className="practice-session-card mt-4"><p className="eyebrow">{title}</p><p className="practice-source">From {item.sourceLabel}</p>
    {item.kind === 'vocabulary' && <><h2 className="practice-prompt">{item.meaning}</h2>{item.example && <p className="section-description">Context: {item.example.replace(new RegExp(item.term, 'ig'), '_____')}</p>}{revealed ? <div className="practice-answer"><strong>{item.term}</strong><p>{item.example}</p></div> : <button className="button-primary" onClick={() => setRevealed(true)}>Reveal answer</button>}{revealed && !result && <Assessment busy={busy} onChoose={(value) => void submit(value)} />}</>}
    {item.kind === 'dictation' && <><button disabled={busy} className="button-secondary" onClick={() => void play()}><Headphones size={17} />{listened ? 'Replay' : 'Play audio'}</button><label className="form-label mt-5 block">What did you hear?<textarea className="form-textarea mt-2" value={response} onChange={event => setResponse(event.target.value)} disabled={Boolean(result)} /></label>{!result && <button disabled={!response.trim() || busy} className="button-primary mt-4" onClick={() => void submit()}>Check answer</button>}{result && <div className="practice-answer"><strong>{result.exactMatch ? 'Exact' : (result.similarityPercent ?? 0) >= 80 ? 'Almost there' : 'Needs review'} · {result.similarityPercent}% word-position match</strong><p>{result.expectedText}</p><div className="word-diff">{result.wordDiff.map((word, index) => <span key={`${word.word}-${index}`} className={word.status}>{word.word}</span>)}</div></div>}</>}
    {item.kind === 'mistake_repair' && <><ol className="practice-step-labels"><li><strong>Recognize</strong><span>Notice what can be improved.</span></li><li><strong>Rebuild</strong><span>Type the complete corrected phrase.</span></li><li><strong>Say it</strong><span>Record the repaired phrase once.</span></li></ol><p className="practice-prompt">{item.original}</p><button className="button-secondary" onClick={() => setRevealed(true)}>Show the repair</button>{revealed && <div className="practice-answer"><strong>{item.corrected}</strong><p>{item.explanation}</p><button disabled={busy} className="text-link" onClick={() => void play()}><Volume2 size={16} /> Hear the corrected phrase</button></div>}{revealed && <label className="form-label mt-5 block">Rebuild the phrase<textarea className="form-textarea mt-2" value={response} onChange={event => setResponse(event.target.value)} /></label>}{revealed && response.trim() && <div className="mt-4"><RecordButton recorder={recorder} /></div>}{pronunciation && <div className="practice-answer"><strong>{pronunciation.overallScore == null ? 'Acoustic feedback unavailable' : `${Math.round(pronunciation.overallScore)}% acoustic match`}</strong><p>This practice does not automatically resolve the recurring mistake.</p></div>}{pronunciation && !result && <Assessment busy={busy} onChoose={(value) => void submit(value)} />}</>}
    {item.kind === 'shadowing' && <><h2 className="practice-prompt">{item.targetText}</h2>{item.hint && <p className="section-description">{item.hint}</p>}<div className="flex flex-wrap gap-3"><button disabled={busy} className="button-secondary" onClick={() => void play()}><Volume2 size={17} />{listened ? 'Replay reference' : 'Listen first'}</button><RecordButton recorder={recorder} disabled={!listened} /></div>{pronunciation && <div className="practice-answer"><strong>{pronunciation.overallScore == null ? 'Feedback unavailable' : `${Math.round(pronunciation.overallScore)}% acoustic match`}</strong><p>{pronunciation.confidence === 'low' ? 'Alignment confidence was low; use this as a gentle practice signal.' : 'Compare the sounds, then try once more if useful.'}</p><WordFeedbackSummary attempt={pronunciation} /></div>}{pronunciation && !result && <button className="button-primary mt-4" onClick={() => void submit()}>Save this attempt</button>}</>}
    {item.kind === 'speaking_recall' && <><p className="practice-situation">{item.situation}</p><h2 className="practice-prompt">{item.prompt}</h2><RecordButton recorder={recorder} />{response && <div className="practice-answer"><span>Your local transcript</span><strong>{response}</strong></div>}<button disabled={!response.trim()} className="button-secondary mt-4" onClick={() => setRevealed(true)}>Reveal a model expression</button>{revealed && <div className="practice-answer"><strong>{item.modelExpression}</strong><p>{containsExpression(response, item.modelExpression) ? 'The exact model expression appeared in your transcript.' : 'No exact model-expression match; this is retrieval practice, not pass/fail.'}</p><button disabled={busy} className="text-link" onClick={() => void play()}><Volume2 size={16} /> Hear model</button></div>}{revealed && response && !result && <button className="button-primary mt-4" onClick={() => void submit()}>Save recall</button>}</>}
    {recorder.error && <InlineNotice tone="error" live>{recorder.error}</InlineNotice>}
    {result && <button className="button-primary mt-6" onClick={next}>Next item</button>}
  </AppCard>
}
function Assessment({ busy, onChoose }: { busy: boolean; onChoose: (value: string) => void }) { return <div className="practice-assessment"><span>How did recall feel?</span><button disabled={busy} onClick={() => onChoose('again')}>Again</button><button disabled={busy} onClick={() => onChoose('review')}>Needs review</button><button disabled={busy} onClick={() => onChoose('comfortable')}>Comfortable</button></div> }
function RecordButton({ recorder, disabled = false }: { recorder: ReturnType<typeof useGuidedLessonRecorder>; disabled?: boolean }) { return recorder.state === 'recording' ? <button className="button-primary" onClick={() => void recorder.stop()}><Square size={16} /> Stop</button> : <button disabled={disabled || recorder.state === 'processing'} className="button-primary" onClick={() => void recorder.start()}><Mic2 size={16} />{recorder.state === 'processing' ? 'Processing…' : 'Record'}</button> }
function WordFeedbackSummary({ attempt }: { attempt: PronunciationAttempt }) { const feedback = wordFeedback(attempt); if (!feedback.available) return <p>Word-level feedback unavailable for this attempt.</p>; const focus = feedback.items.filter(item => item.focus); return <p>{focus.length ? `Focus words: ${focus.map(item => `${item.word.word} (${item.label})`).join(', ')}` : 'No specific focus words were identified.'}</p> }
function comparable(value: string) { return value.toLocaleLowerCase('en-US').replace(/[‘’ʼ]/g, "'").replace(/[^\p{L}\p{N}'\s]/gu, ' ').replace(/\s+/g, ' ').trim() }
function containsExpression(response: string, target: string) { const normalizedTarget = comparable(target); return normalizedTarget.length > 0 && comparable(response).includes(normalizedTarget) }
function label(value: string) { return value.split('_').map(part => part[0].toUpperCase() + part.slice(1)).join(' ') }
function message(value: unknown) { return value instanceof Error ? value.message : String(value) }
