import { AlertTriangle, CheckCircle2, Play, RotateCcw, Volume2, XCircle } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { InlineNotice, PageShell } from '../components/ProductUI'
import { advanceToeicPart2Session, cancelToeicPart2Audio, completeToeicPart2Audio, getToeicPart2Session, prepareToeicPart2Audio, submitToeicPart2Answer } from '../services/native'
import type { ToeicAudio, ToeicPart2Feedback, ToeicPart2Session } from '../types'

export function ToeicPart2SessionPage(){
  const {sessionId=''}=useParams();const navigate=useNavigate();const query=new URLSearchParams(location.search);const fullId=query.get('fullListening');const practiceId=query.get('toeicPractice');const practiceLimit=Number(query.get('limit'));const simulation=fullId!==null&&query.get('mode')==='simulation';const[session,setSession]=useState<ToeicPart2Session|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[playing,setPlaying]=useState(false);const[details,setDetails]=useState(false);const active=useRef<{element:HTMLAudioElement;data:ToeicAudio}|null>(null)
  const load=useCallback(()=>{setError(null);void getToeicPart2Session(sessionId).then(value=>value.status==='completed'?navigate(fullId?`/toeic/listening/${fullId}`:`/toeic/part2/results/${sessionId}`,{replace:true}):setSession(value)).catch(value=>setError(msg(value)))},[navigate,sessionId]);useEffect(load,[load]);useEffect(()=>()=>{if(active.current){active.current.element.pause();void cancelToeicPart2Audio(active.current.data)}},[])
  if(error&&!session)return <ErrorState message={error} onRetry={load}/>;if(!session)return <LoadingState label="Restoring TOEIC Part 2…"/>;const q=session.currentQuestion;if(!q)return <ErrorState message="The current question could not be restored." onRetry={load}/>
  const play=async()=>{setBusy(true);setError(null);try{const data=await prepareToeicPart2Audio(session.sessionId);const element=new Audio(`data:${data.mimeType};base64,${data.audioBase64}`);active.current={element,data};setPlaying(true);element.onended=()=>{setPlaying(false);active.current=null;void completeToeicPart2Audio(data,session.sessionId).then(setSession).catch(value=>setError(msg(value)))};element.onerror=()=>{setPlaying(false);active.current=null;void cancelToeicPart2Audio(data);setError('The local audio could not be played. Try again from the beginning.')};await element.play()}catch(value){setError(msg(value))}finally{setBusy(false)}}
  const answer=async(choice:string)=>{setBusy(true);try{let updated=await submitToeicPart2Answer(session.sessionId,q.itemId,q.itemVersion,choice);if(simulation&&updated.feedback){updated=await advanceToeicPart2Session(updated.sessionId);if(updated.status==='completed'){navigate(`/toeic/listening/${fullId}`);return}}setSession(updated)}catch(value){setError(msg(value))}finally{setBusy(false)}}
  const next=async()=>{if(practiceId&&session.answeredCount>=practiceLimit){navigate(`/toeic/personalized/${practiceId}`);return}setBusy(true);try{const value=await advanceToeicPart2Session(session.sessionId);if(value.status==='completed'){navigate(fullId?`/toeic/listening/${fullId}`:`/toeic/part2/results/${session.sessionId}`)}else{setSession(value);setDetails(false)}}catch(value){setError(msg(value))}finally{setBusy(false)}};const f=simulation?null:session.feedback;const reveal=!!f&&(!f.isCorrect||details)
  return <PageShell width="standard"><div className="toeic-session-head"><button className="button-ghost" onClick={()=>navigate(fullId?`/toeic/listening/${fullId}`:'/toeic')}>← Save & exit</button><div><strong>TOEIC Listening Part 2</strong><span>Question {q.questionNumber} of 25</span></div><span className="toeic-untimed">Untimed</span></div><div className="toeic-progress"><span style={{width:`${q.questionNumber*4}%`}}/></div>{error&&<InlineNotice tone="warning" live>{error}</InlineNotice>}{q.initialAudioInterrupted&&!q.initialAudioCompleted&&!f&&<InlineNotice tone="info"><AlertTriangle/>Audio interrupted. Restart it from the beginning with no penalty.</InlineNotice>}<section className="toeic-question-card toeic-part2-card"><div className="toeic-question-controls"><p className="eyebrow">Listening Part 2 · Question–Response</p><h1>Listen to the question and three responses. Choose the best response.</h1>{!f&&<><button className="toeic-audio-button" disabled={busy||playing||q.initialAudioCompleted} onClick={()=>void play()}>{playing?<Volume2 className="toeic-pulse"/>:<Play fill="currentColor"/>}{playing?'Playing question and A–C…':q.initialAudioCompleted?'Audio played':'Play once'}</button><p className="muted toeic-audio-note">The prompt and responses remain hidden until your answer is locked.</p><div className="toeic-answer-grid">{q.choices.map(choice=><button aria-label={`Choose answer ${choice}`} disabled={busy||playing||!q.initialAudioCompleted} onClick={()=>void answer(choice)} key={choice}>{choice}</button>)}</div></>}{f&&<div className={`toeic-feedback ${f.isCorrect?'correct':'incorrect'}`}><div className="toeic-feedback-title">{f.isCorrect?<CheckCircle2/>:<XCircle/>}<div><h2>{f.isCorrect?'Correct':'Incorrect'}</h2><p>Your first answer is locked for scoring.</p></div></div>{!f.isCorrect&&<p><strong>Correct answer: {f.correctAnswer}</strong></p>}<div className="toeic-feedback-actions"><button className="button-secondary" disabled={playing||busy} onClick={()=>void play()}><RotateCcw/>Replay</button>{f.isCorrect&&!reveal&&<button className="button-ghost" onClick={()=>setDetails(true)}>Review explanation</button>}</div>{reveal&&<Feedback feedback={f}/>}<button className="button-primary toeic-next" disabled={busy||playing} onClick={()=>void next()}>{q.questionNumber===25?'Complete Part 2':'Continue'} →</button></div>}</div></section></PageShell>
}
function Feedback({feedback:f}:{feedback:ToeicPart2Feedback}){return <div className="toeic-explanation"><h3>Transcript</h3><p><strong>Question:</strong> “{f.prompt}”</p><ol>{f.responses.map(r=><li className={r.choice===f.correctAnswer?'is-correct':r.choice===f.selectedChoice?'is-selected':''} key={r.choice}><b>{r.choice}</b><span>“{r.text}”</span></li>)}</ol><h3>Why {f.correctAnswer} is correct</h3><p>{f.correctExplanation}</p>{f.selectedExplanation&&<><h3>Why {f.selectedChoice} is incorrect</h3><p>{f.selectedExplanation}</p></>}<h3>Listening focus</h3><div className="toeic-tags">{f.listeningFocus.map(x=><span key={x}>{x}</span>)}</div>{f.usefulPattern&&<p><strong>Useful pattern:</strong> {f.usefulPattern}</p>}</div>}function msg(value:unknown){return value instanceof Error?value.message:String(value)}


