import { AlertTriangle, CheckCircle2, Play, RotateCcw, Volume2, XCircle } from 'lucide-react'
import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { InlineNotice, PageShell } from '../components/ProductUI'
import { advanceToeicSession, cancelToeicAudio, completeToeicAudio, getToeicSession, prepareToeicAudio, recordToeicActiveTime, submitToeicAnswer } from '../services/native'
import type { ToeicAudio, ToeicSession } from '../types'

export function ToeicSessionPage(){
  const {sessionId=''}=useParams();const navigate=useNavigate();const query=new URLSearchParams(location.search);const fullId=query.get('fullListening');const simulation=fullId!==null&&query.get('mode')==='simulation';const [session,setSession]=useState<ToeicSession|null>(null);const [error,setError]=useState<string|null>(null);const [busy,setBusy]=useState(false);const [playing,setPlaying]=useState(false);const [showDetails,setShowDetails]=useState(false);const activeAudio=useRef<{element:HTMLAudioElement;data:ToeicAudio}|null>(null)
  const load=useCallback(()=>{setError(null);void getToeicSession(sessionId).then(value=>{if(value.status==='completed')navigate(fullId?`/toeic/listening/${fullId}`:`/toeic/results/${sessionId}`,{replace:true});else setSession(value)}).catch(value=>setError(message(value)))},[navigate,sessionId])
  useEffect(load,[load])
  const activeSessionId=session?.sessionId
  useEffect(()=>{if(!activeSessionId||document.visibilityState!=='visible')return;const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void recordToeicActiveTime(activeSessionId,crypto.randomUUID(),15)},15000);return()=>window.clearInterval(timer)},[activeSessionId])
  useEffect(()=>()=>{const current=activeAudio.current;if(current){current.element.pause();void cancelToeicAudio(current.data)}},[])
  if(error&&!session)return <ErrorState message={error} onRetry={load}/>
  if(!session)return <LoadingState label="Restoring your TOEIC practice…"/>
  const question=session.currentQuestion;if(!question)return <ErrorState message="The current question could not be restored." onRetry={load}/>
  const play=async()=>{setBusy(true);setError(null);try{const data=await prepareToeicAudio(session.sessionId);const audio=new Audio(`data:${data.mimeType};base64,${data.audioBase64}`);activeAudio.current={element:audio,data};setPlaying(true);audio.onended=()=>{setPlaying(false);activeAudio.current=null;void completeToeicAudio(data,session.sessionId).then(setSession).catch(value=>setError(message(value)))};audio.onerror=()=>{setPlaying(false);activeAudio.current=null;void cancelToeicAudio(data);setError('The local audio could not be played. You may try again without penalty.')};await audio.play()}catch(value){setError(message(value))}finally{setBusy(false)}}
  const answer=async(choice:string)=>{setBusy(true);setError(null);try{let updated=await submitToeicAnswer(session.sessionId,question.itemId,question.itemVersion,choice);if(simulation&&updated.feedback){updated=await advanceToeicSession(updated.sessionId);if(updated.status==='completed'){navigate(`/toeic/listening/${fullId}`);return}}setSession(updated)}catch(value){setError(message(value))}finally{setBusy(false)}}
  const next=async()=>{setBusy(true);setError(null);try{const updated=await advanceToeicSession(session.sessionId);if(updated.status==='completed')navigate(fullId?`/toeic/listening/${fullId}`:`/toeic/results/${session.sessionId}`);else{setSession(updated);setShowDetails(false)}}catch(value){setError(message(value))}finally{setBusy(false)}}
  const feedback=simulation?null:session.feedback;const showFeedbackDetails=feedback&&!feedback.isCorrect||showDetails
  return <PageShell width="standard"><div className="toeic-session-head"><button className="button-ghost" onClick={()=>navigate(fullId?`/toeic/listening/${fullId}`:'/toeic')}>← Save & exit</button><div><strong>{session.formTitle}</strong><span>Question {question.questionNumber} of {question.totalQuestions}</span></div><span className="toeic-untimed">Untimed</span></div>
    <div className="toeic-progress" aria-label={`${question.questionNumber} of ${question.totalQuestions}`}><span style={{width:`${question.questionNumber/question.totalQuestions*100}%`}}/></div>
    {error&&<InlineNotice tone="warning" live>{error}</InlineNotice>}{question.initialAudioInterrupted&&!question.initialAudioCompleted&&!feedback&&<InlineNotice tone="info"><AlertTriangle/>The previous audio was interrupted. Play it again from the beginning—there is no penalty.</InlineNotice>}
    <section className="toeic-question-card"><img className="toeic-photo" src={`data:${question.imageMimeType};base64,${question.imageBase64}`} alt={`TOEIC-style workplace scene for question ${question.questionNumber}`}/><div className="toeic-question-controls"><p className="eyebrow">Listening Part 1 · Photograph</p><h1>Choose the statement that best describes the photograph.</h1>{!feedback&&<><button className="toeic-audio-button" disabled={busy||playing||question.initialAudioCompleted} onClick={()=>void play()}>{playing?<Volume2 className="toeic-pulse"/>:<Play fill="currentColor"/>}{playing?'Playing A–D…':question.initialAudioCompleted?'Audio played':'Play statements once'}</button><p className="muted toeic-audio-note">Statements stay hidden until you answer. Listen to all four before choosing.</p><div className="toeic-answer-grid" aria-label="Answer choices">{question.choices.map(choice=><button aria-label={`Choose answer ${choice}`} disabled={busy||playing||!question.initialAudioCompleted} onClick={()=>void answer(choice)} key={choice}>{choice}</button>)}</div></>}
      {feedback&&<div className={`toeic-feedback ${feedback.isCorrect?'correct':'incorrect'}`}><div className="toeic-feedback-title">{feedback.isCorrect?<CheckCircle2/>:<XCircle/>}<div><h2>{feedback.isCorrect?'Correct':'Incorrect'}</h2><p>Your first answer is locked for scoring.</p></div></div>{!feedback.isCorrect&&<p><strong>Correct answer: {feedback.correctAnswer}</strong></p>}<div className="toeic-feedback-actions"><button className="button-secondary" disabled={playing||busy} onClick={()=>void play()}><RotateCcw/>Listen again</button>{feedback.isCorrect&&!showDetails&&<button className="button-ghost" onClick={()=>setShowDetails(true)}>Review explanation</button>}</div>{showFeedbackDetails&&<FeedbackDetails feedback={feedback}/>}<button className="button-primary toeic-next" disabled={busy||playing} onClick={()=>void next()}>{question.questionNumber===6?'Complete Part 1':'Continue'} →</button></div>}
    </div></section>
  </PageShell>
}
function FeedbackDetails({feedback}:{feedback:NonNullable<ToeicSession['feedback']>}){return <div className="toeic-explanation"><h3>Transcript</h3><ol>{feedback.statements.map(s=><li className={s.choice===feedback.correctAnswer?'is-correct':s.choice===feedback.selectedChoice?'is-selected':''} key={s.choice}><b>{s.choice}</b><span>“{s.text}”</span></li>)}</ol><h3>Why {feedback.correctAnswer} is correct</h3><p>{feedback.correctExplanation}</p>{feedback.selectedExplanation&&<><h3>Why your answer {feedback.selectedChoice} is incorrect</h3><p>{feedback.selectedExplanation}</p></>}<h3>Language focus</h3><ul>{feedback.languageFocus.map(value=><li key={value}>{value}</li>)}</ul>{feedback.usefulVocabulary.length>0&&<><h3>Useful vocabulary</h3><div className="toeic-tags">{feedback.usefulVocabulary.map(value=><span key={value}>{value}</span>)}</div></>}</div>}
function message(value:unknown){return value instanceof Error?value.message:String(value)}


