import { BookOpenCheck, Check, Clock3, Headphones, History, LockKeyhole } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { AppCard, InlineNotice, PageHero, PageShell, SectionHeader } from '../components/ProductUI'
import { getToeicOverview, getToeicPart2Overview, startToeicPart2Session, startToeicSession } from '../services/native'
import type { ToeicOverview, ToeicPart2Overview } from '../types'
export function ToeicPage(){const nav=useNavigate();const[data,setData]=useState<ToeicOverview|null>(null);const[p2,setP2]=useState<ToeicPart2Overview|null>(null);const[error,setError]=useState<string|null>(null);const[busy,setBusy]=useState<string|null>(null);const load=()=>{setError(null);void Promise.all([getToeicOverview(),getToeicPart2Overview()]).then(([a,b])=>{setData(a);setP2(b)}).catch(v=>setError(msg(v)))};useEffect(load,[]);if(error&&!data)return <ErrorState message={error} onRetry={load}/>;if(!data||!p2)return <LoadingState label="Loading the local TOEIC item bank…"/>;const start=async(id:string,v:number,part2=false)=>{setBusy(id);try{if(part2){const s=await startToeicPart2Session(id,v);nav(`/toeic/part2/session/${s.sessionId}`)}else{const s=await startToeicSession(id,v);nav(`/toeic/session/${s.sessionId}`)}}catch(x){setError(msg(x))}finally{setBusy(null)}};return <PageShell width="wide"><PageHero eyebrow="Exam preparation" title="TOEIC Preparation" accent="Listening & Reading" description="Focused, offline TOEIC-style practice with deterministic grading and authored feedback. Listening Parts 1 and 2 are available." compact/>{error&&<InlineNotice tone="warning" live>{error}</InlineNotice>}<div className="toeic-trust-row"><span><Clock3/>Untimed by design</span><span><LockKeyhole/>Answers stored locally</span><span><BookOpenCheck/>Authored explanations</span></div><Forms title="Listening Part 1 — Photographs" description="Look at each photograph, listen once to four statements, and choose the best description." forms={data.forms} total={6} busy={busy} onOpen={(id,v,active)=>active?nav(`/toeic/session/${active}`):void start(id,v)}/><Forms title="Listening Part 2 — Question–Response" description="Listen once to a prompt and three spoken responses, then choose the best response." forms={p2.forms} total={25} busy={busy} onOpen={(id,v,active)=>active?nav(`/toeic/part2/session/${active}`):void start(id,v,true)}/><AppCard className="mt-4"><div className="section-header"><div><p className="eyebrow">Full exam architecture</p><h2 className="section-title">Listening & Reading · 200 questions</h2><p className="section-description">Parts 1 and 2 are available; later parts are not yet available.</p></div><button className="button-secondary" onClick={()=>nav('/toeic/history')}><History/>TOEIC Performance</button></div><div className="toeic-parts-grid">{data.parts.map((part,index)=>{const available=part.runtimeAvailable||part.part==='part2_question_response';return <div className={`toeic-part-row ${available?'available':''}`} key={part.part}><span>{available?<Check/>:<LockKeyhole/>}</span><div><strong>Part {index+1} — {part.title}</strong><small>{part.questionCount} questions</small></div><b>{available?'Available':'Not yet available'}</b></div>})}</div></AppCard><p className="toeic-disclaimer">{data.disclaimer}</p></PageShell>}
function Forms({title,description,forms,total,busy,onOpen}:{title:string;description:string;forms:Array<{formId:string;formVersion:number;title:string;activeSessionId:string|null}>;total:number;busy:string|null;onOpen:(id:string,v:number,a:string|null)=>void}){return <AppCard className="mt-4"><SectionHeader title={title} description={description}/><div className="toeic-form-grid">{forms.map(f=><article className="toeic-form-card" key={f.formId}><div className="toeic-part-icon"><Headphones/></div><div><p className="eyebrow">{total} questions · Untimed</p><h3>{f.title}</h3><p>Original local content with deterministic scoring and explanations.</p></div><button className="button-primary" disabled={busy!==null} onClick={()=>onOpen(f.formId,f.formVersion,f.activeSessionId)}>{f.activeSessionId?'Resume':busy===f.formId?'Starting…':'Start form'}</button></article>)}</div></AppCard>}function msg(v:unknown){return v instanceof Error?v.message:String(v)}
