import { BarChart3, BookOpen, CheckCircle2, Headphones, RotateCcw } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { AppCard, InlineNotice, PageShell } from '../components/ProductUI'
import { getToeicPart2Result, getToeicPart2Review } from '../services/native'
import type { ToeicBreakdown, ToeicPart2Result, ToeicPart2ReviewItem } from '../types'
export function ToeicPart2ResultsPage(){const{sessionId=''}=useParams();const nav=useNavigate();const[result,setResult]=useState<ToeicPart2Result|null>(null);const[review,setReview]=useState<ToeicPart2ReviewItem[]|null>(null);const[error,setError]=useState<string|null>(null);const load=()=>{setError(null);void getToeicPart2Result(sessionId).then(setResult).catch(v=>setError(msg(v)))};useEffect(load,[sessionId]);const reviewNow=async(mistakes:boolean)=>{try{setReview(await getToeicPart2Review(sessionId,mistakes))}catch(v){setError(msg(v))}};if(error&&!result)return <ErrorState message={error} onRetry={load}/>;if(!result)return <LoadingState label="Calculating deterministic Part 2 results…"/>;return <PageShell width="wide"><section className="toeic-result-hero"><div><p className="eyebrow">Part 2 complete</p><h1>{result.correct} / 25</h1><strong>{result.accuracy}% accuracy</strong></div><div className="toeic-score-ring" style={{'--score':`${result.accuracy*3.6}deg`} as React.CSSProperties}><span>{result.accuracy}%</span></div></section>{error&&<InlineNotice tone="warning">{error}</InlineNotice>}<InlineNotice tone="info"><BarChart3/>{result.scoreMessage}</InlineNotice><div className="toeic-results-grid"><AppCard><h2>By difficulty</h2>{result.difficultyBreakdown.map(x=><Bar key={x.label} {...x}/>)}</AppCard><AppCard><h2>By prompt type</h2>{result.promptBreakdown.map(x=><Bar key={x.label} {...x}/>)}</AppCard><AppCard><h2>Distractor patterns</h2>{result.distractorBreakdown.length?result.distractorBreakdown.map(x=><div className="toeic-result-line" key={x.label}><span>{pretty(x.label)}</span><b>{x.total}</b></div>):<p className="muted">No incorrect distractors selected.</p>}</AppCard></div><div className="toeic-result-actions"><button className="button-primary" onClick={()=>void reviewNow(true)}><RotateCcw/>Review mistakes</button><button className="button-secondary" onClick={()=>void reviewNow(false)}><BookOpen/>Review all</button><button className="button-ghost" onClick={()=>nav('/toeic')}><Headphones/>Back to TOEIC</button></div>{review&&<section className="toeic-review-section">{review.length===0?<AppCard><CheckCircle2/> No mistakes in this form.</AppCard>:review.map(x=><AppCard key={x.questionNumber} className="toeic-review-item"><div><p className="eyebrow">Question {x.questionNumber} · {x.difficulty}</p><h3>{x.feedback.isCorrect?'Correct':`Your answer: ${x.feedback.selectedChoice} · Correct: ${x.feedback.correctAnswer}`}</h3><p><strong>Question:</strong> “{x.feedback.prompt}”</p><ol>{x.feedback.responses.map(r=><li key={r.choice}><b>{r.choice}</b> “{r.text}”</li>)}</ol><p>{x.feedback.correctExplanation}</p><div className="toeic-tags">{x.tags.map(t=><span key={t}>{pretty(t)}</span>)}</div></div></AppCard>)}</section>}</PageShell>}
function Bar({label,correct,total}:ToeicBreakdown){return <div className="toeic-result-bar"><div><span>{pretty(label)}</span><b>{correct}/{total}</b></div><div><i style={{width:`${total?correct/total*100:0}%`}}/></div></div>}function pretty(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function msg(v:unknown){return v instanceof Error?v.message:String(v)}
