import { ArrowLeft,CheckCircle2,ChevronDown,ChevronRight,XCircle } from 'lucide-react'
import { useCallback,useEffect,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { ErrorState,LoadingState } from '../components/PageState'
import { AppCard,InlineNotice,PageShell } from '../components/ProductUI'
import { advanceToeicPart5Session,getToeicPart5Session,submitToeicPart5Answer } from '../services/native'
import type { ToeicPart5Feedback,ToeicPart5Session } from '../types'

export function ToeicPart5SessionPage(){const{sessionId=''}=useParams();const nav=useNavigate();const[s,setS]=useState<ToeicPart5Session|null>(null);const[selected,setSelected]=useState<string|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState<string|null>(null);const[details,setDetails]=useState(false);const load=useCallback(()=>{setError(null);void getToeicPart5Session(sessionId).then(x=>x.status==='completed'?nav(`/toeic/part5/results/${sessionId}`,{replace:true}):setS(x)).catch(x=>setError(msg(x)))},[nav,sessionId]);useEffect(load,[load]);if(error&&!s)return <ErrorState message={error} onRetry={load}/>;if(!s)return <LoadingState label="Restoring TOEIC Reading Part 5…"/>;const q=s.currentQuestion;if(!q)return <ErrorState message="The current Part 5 question could not be restored." onRetry={load}/>;const submit=async()=>{if(!selected)return;setBusy(true);setError(null);try{setS(await submitToeicPart5Answer(s.sessionId,q.itemId,q.itemVersion,selected))}catch(x){setError(msg(x))}finally{setBusy(false)}};const next=async()=>{setBusy(true);try{const x=await advanceToeicPart5Session(s.sessionId);if(x.status==='completed')nav(`/toeic/part5/results/${s.sessionId}`);else{setS(x);setSelected(null);setDetails(false)}}catch(x){setError(msg(x))}finally{setBusy(false)}};return <PageShell width="standard"><div className="toeic-session-head"><button className="button-ghost" onClick={()=>nav('/toeic')}><ArrowLeft/>Save & exit</button><div><strong>Reading Part 5 — Incomplete Sentences</strong><span>Question {q.questionNumber} of 30 · {s.answeredCount}/30 answered</span></div><span className="toeic-untimed">Untimed</span></div><div className="toeic-progress" aria-label={`${q.questionNumber} of 30`}><span style={{width:`${q.questionNumber/30*100}%`}}/></div>{error&&<InlineNotice tone="warning" live>{error}</InlineNotice>}<AppCard className="toeic-part5-card"><p className="eyebrow">Choose the best answer</p><h1>{q.sentence}</h1><fieldset className="toeic-part5-choices" disabled={busy||!!s.feedback}><legend className="sr-only">Answer choices</legend>{q.choices.map(c=><label className={selected===c.choice?'selected':''} key={c.choice}><input type="radio" name="part5-answer" value={c.choice} checked={selected===c.choice} onChange={()=>setSelected(c.choice)}/><b>{c.choice}</b><span>{c.text}</span></label>)}</fieldset>{!s.feedback&&<button className="button-primary toeic-part5-submit" disabled={!selected||busy} onClick={()=>void submit()}>Submit Answer</button>}{s.feedback&&<Feedback feedback={s.feedback} details={details} setDetails={setDetails} next={()=>void next()} busy={busy} final={q.questionNumber===30}/>}</AppCard></PageShell>}
function Feedback({feedback:f,details,setDetails,next,busy,final}:{feedback:ToeicPart5Feedback;details:boolean;setDetails:(x:boolean)=>void;next:()=>void;busy:boolean;final:boolean}){return <section className={`toeic-part5-feedback ${f.isCorrect?'correct':'incorrect'}`} aria-live="polite"><header>{f.isCorrect?<CheckCircle2/>:<XCircle/>}<div><h2>{f.isCorrect?'Correct':'Incorrect'}</h2><p>Your first answer is locked for scoring.</p></div></header>{!f.isCorrect&&<div className="toeic-part5-answer-compare"><p><small>Your answer</small><strong>{f.selectedChoice}</strong></p><p><small>Correct answer</small><strong>{f.correctChoice}</strong></p></div>}<div className="toeic-complete-sentence"><small>Complete sentence</small><p>{f.completeSentence}</p></div>{(!f.isCorrect||details)&&<div className="toeic-explanation"><h3>Why {f.correctChoice} is correct</h3><p>{f.correctExplanation}</p>{f.selectedDistractorExplanation&&<><h3>Why {f.selectedChoice} does not work</h3><p>{f.selectedDistractorExplanation}</p></>}<p><strong>Focus:</strong> {pretty(f.skillSubcategory)}</p>{f.usefulPattern&&<p><strong>Useful pattern:</strong> {f.usefulPattern}</p>}{f.extraExample&&<p><strong>Extra example:</strong> {f.extraExample}</p>}{f.otherDistractorExplanations.length>0&&<details><summary>Why the other options do not work</summary>{f.otherDistractorExplanations.map(x=><p key={x.choice}><strong>{x.choice}) {x.text}:</strong> {x.explanation}</p>)}</details>}</div>}{f.isCorrect&&!details&&<button className="button-secondary" onClick={()=>setDetails(true)}><ChevronDown/>View explanation</button>}<button className="button-primary toeic-next" disabled={busy} onClick={next}>{final?'Complete Part 5':'Next Question'}<ChevronRight/></button></section>}
function pretty(x:string){return x.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())}function msg(x:unknown){return x instanceof Error?x.message:String(x)}
