import { AlertTriangle, CheckCircle2, Play, RotateCcw, XCircle } from 'lucide-react'
import { useCallback,useEffect,useRef,useState } from 'react'
import { useNavigate,useParams } from 'react-router-dom'
import { ErrorState,LoadingState } from '../components/PageState'
import { AppCard,InlineNotice,PageShell } from '../components/ProductUI'
import { advanceToeicPart4Session,cancelToeicPart4Audio,completeToeicPart4Audio,getToeicPart4Session,prepareToeicPart4Audio,submitToeicPart4Answer } from '../services/native'
import type { ToeicPart4Audio,ToeicPart4Feedback,ToeicPart4Graphic,ToeicPart4Session } from '../types'
export function ToeicPart4SessionPage(){const{sessionId=''}=useParams();const nav=useNavigate();const query=new URLSearchParams(location.search);const fullId=query.get('fullListening');const simulation=fullId!==null&&query.get('mode')==='simulation';const[s,setS]=useState<ToeicPart4Session|null>(null);const[error,setError]=useState<string|null>(null);const[playing,setPlaying]=useState(false);const[busy,setBusy]=useState(false);const active=useRef<{audio:HTMLAudioElement;data:ToeicPart4Audio}|null>(null);const load=useCallback(()=>{setError(null);void getToeicPart4Session(sessionId).then(x=>{if(x.status==='completed')nav(fullId?`/toeic/listening/${fullId}`:`/toeic/part4/results/${sessionId}`,{replace:true});else setS(x)}).catch(x=>setError(msg(x)))},[nav,sessionId]);useEffect(load,[load]);useEffect(()=>()=>{if(active.current){active.current.audio.pause();void cancelToeicPart4Audio(active.current.data)}},[]);if(error&&!s)return <ErrorState message={error} onRetry={load}/>;if(!s)return <LoadingState label="Restoring TOEIC Part 4Ã¢â‚¬Â¦"/>;const set=s.currentSet;if(!set)return <ErrorState message="The current talk could not be restored." onRetry={load}/>;
const play=async()=>{setBusy(true);setError(null);let pid:string|null=null;setPlaying(true);try{for(let turn=0;;turn++){const data=await prepareToeicPart4Audio(s.sessionId,turn,pid);pid=data.presentationId;await new Promise<void>((resolve,reject)=>{const audio=new Audio(`data:${data.mimeType};base64,${data.audioBase64}`);active.current={audio,data};audio.onended=()=>{void completeToeicPart4Audio(data,s.sessionId).then(updated=>{setS(updated);active.current=null;resolve()}).catch(reject)};audio.onerror=()=>reject(new Error('The local talk audio could not be played.'));void audio.play().catch(reject)});if(turn+1===data.turnCount)break}}catch(x){if(active.current)void cancelToeicPart4Audio(active.current.data);setError(msg(x))}finally{active.current=null;setPlaying(false);setBusy(false)}};
const answer=async(q:string,c:string)=>{setBusy(true);try{let x=await submitToeicPart4Answer(s.sessionId,q,c);if(simulation&&x.feedback){x=await advanceToeicPart4Session(x.sessionId);if(x.status==='completed'){nav(`/toeic/listening/${fullId}`);return}}setS(x)}catch(x){setError(msg(x))}finally{setBusy(false)}};const next=async()=>{setBusy(true);try{const x=await advanceToeicPart4Session(s.sessionId);if(x.status==='completed')nav(fullId?`/toeic/listening/${fullId}`:`/toeic/part4/results/${s.sessionId}`);else setS(x)}catch(x){setError(msg(x))}finally{setBusy(false)}};
return <PageShell width="wide"><div className="toeic-session-head"><button className="button-ghost" onClick={()=>nav(fullId?`/toeic/listening/${fullId}`:'/toeic')}>Ã¢â€ Â Save & exit</button><div><strong>Part 4 Ã¢â‚¬â€ Talks</strong><span>Talk {set.setNumber} of 10 Ã‚Â· {s.answeredCount}/30 answered</span></div><span className="toeic-untimed">Untimed</span></div><div className="toeic-progress"><span style={{width:`${set.setNumber/10*100}%`}}/></div><InlineNotice tone="info">You can pause freely between talks. Once audio starts, try to complete all three questions before leaving.</InlineNotice>{error&&<InlineNotice tone="warning" live>{error}</InlineNotice>}{set.initialAudioInterrupted&&!set.initialAudioCompleted&&<InlineNotice tone="info"><AlertTriangle/>Playback was interrupted. It can restart from the beginning without penalty.</InlineNotice>}<div className="toeic-part4-layout"><section><AppCard><p className="eyebrow">Talk {set.setNumber}</p><h1>Read the questions, then play the talk once.</h1>{set.graphic&&<Graphic graphic={set.graphic}/>}<button className="toeic-audio-button" disabled={busy||playing||(!s.feedback&&set.initialAudioCompleted)} onClick={()=>void play()}>{s.feedback?<RotateCcw/>:<Play fill="currentColor"/>}{playing?'Playing talkÃ¢â‚¬Â¦':s.feedback?'Listen again':set.initialAudioCompleted?'Talk played':'Play talk once'}</button></AppCard>{set.questions.map((q,i)=><AppCard key={q.questionId} className="mt-4"><p className="eyebrow">Question {i+1}</p><h2>{q.text}</h2><div className="toeic-part4-choices">{q.choices.map(c=><button className={q.selectedChoice===c.choice?'selected':''} disabled={busy||playing||!set.initialAudioCompleted||q.answered} onClick={()=>void answer(q.questionId,c.choice)} key={c.choice}><b>{c.choice}</b><span>{c.text}</span>{q.selectedChoice===c.choice&&<small>Answer recorded</small>}</button>)}</div></AppCard>)}</section>{s.feedback&&!simulation&&<Feedback feedback={s.feedback} onNext={()=>void next()} busy={busy||playing} final={set.setNumber===10}/>}</div></PageShell>}
function Graphic({graphic:g}:{graphic:ToeicPart4Graphic}){return <figure className="toeic-part4-graphic"><figcaption>{g.title}</figcaption><table><thead><tr>{g.columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{g.rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></figure>}
function Feedback({feedback:f,onNext,busy,final}:{feedback:ToeicPart4Feedback;onNext:()=>void;busy:boolean;final:boolean}){const[transcript,setTranscript]=useState(false);return <aside><AppCard><p className="eyebrow">Talk results</p>{f.questions.map((q,i)=><div className={`toeic-part4-feedback ${q.isCorrect?'correct':'incorrect'}`} key={q.questionId}>{q.isCorrect?<CheckCircle2/>:<XCircle/>}<div><h3>Question {i+1}: {q.isCorrect?'Correct':'Incorrect'}</h3>{!q.isCorrect&&<><p>Your answer: {q.selectedChoice} Ã‚Â· Correct: {q.correctAnswer}</p><p><strong>Why:</strong> {q.correctExplanation}</p><p><strong>Evidence:</strong> Ã¢â‚¬Å“{q.evidence}Ã¢â‚¬Â</p><p><strong>Why {q.selectedChoice} is incorrect:</strong> {q.selectedExplanation}</p><p><strong>Notice next time:</strong> {q.noticeNextTime}</p></>}</div></div>)}<button className="button-secondary" onClick={()=>setTranscript(x=>!x)}>{transcript?'Hide':'Show'} talk transcript</button>{transcript&&<div className="toeic-transcript">{f.transcript.map((t,i)=><p key={i}><b>Speaker {t.speaker}:</b> {t.text}</p>)}</div>}<button className="button-primary toeic-next" disabled={busy} onClick={onNext}>{final?'Complete Part 4':'Continue'} Ã¢â€ â€™</button><button className="button-ghost" onClick={()=>location.assign('/toeic')}>Pause & Exit</button></AppCard></aside>}
function msg(x:unknown){return x instanceof Error?x.message:String(x)}


