// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter, Route, Routes } from "react-router-dom";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { ToeicFullLrPage } from "./ToeicFullLrPage";
import { ToeicFullReadingPage } from "./ToeicFullReadingPage";
import { ToeicHistoryPage } from "./ToeicHistoryPage";

const api=vi.hoisted(()=>({listToeicHistory:vi.fn(),listToeicFullReadingHistory:vi.fn(),listToeicFullLrHistory:vi.fn(),getToeicFullReading:vi.fn(),startToeicFullReading:vi.fn(),getToeicFullReadingAggregate:vi.fn(),getToeicFullLr:vi.fn(),startToeicFullLr:vi.fn(),getToeicFullLrAggregate:vi.fn()}));
vi.mock("../services/native",()=>api);
const reading={sessionId:"reading-a",family:"A",mode:"simulation",status:"completed",currentPart:7,answeredCount:100,totalQuestions:100,parts:[5,6,7].map((partNumber)=>({partNumber,title:`Part ${partNumber}`,questionCount:partNumber===5?30:partNumber===6?16:54,sessionId:`p${partNumber}`,status:"completed",route:`/p${partNumber}`})),estimate:{rawCorrect:71,estimatedScore:370,rangeLow:340,rangeHigh:400,profileId:"reading",profileVersion:1,label:"Unofficial"},disclaimer:"Unofficial"};
const full={sessionId:"full-a",family:"A",status:"completed",currentSection:"complete",listeningSessionId:"listening-a",readingSessionId:"reading-a",listeningRaw:79,readingRaw:71,totalRaw:150,listeningEstimate:405,readingEstimate:370,totalEstimate:775,rangeLow:720,rangeHigh:830,listeningRoute:"/toeic/listening/listening-a",readingRoute:"/toeic/reading/reading-a",disclaimer:"Unofficial"};
const parts=[{partNumber:5,sessionId:"p5",result:{correct:22,total:30},review:[{itemId:"q1"}]},{partNumber:6,sessionId:"p6",result:{correct:11,total:16},review:[]},{partNumber:7,sessionId:"p7",result:{correct:38,total:54},review:[]}];
afterEach(cleanup);
beforeEach(()=>{vi.clearAllMocks();api.listToeicHistory.mockResolvedValue([]);api.listToeicFullReadingHistory.mockResolvedValue([{sessionId:"reading-a",mode:"simulation",status:"completed",rawCorrect:71,estimatedScore:370,rangeLow:340,rangeHigh:400,createdAt:"2026-09-01T12:00:00Z",completedAt:"2026-09-01T13:00:00Z",family:"A",answeredCount:100,currentPart:7,scoreProfileVersion:1}]);api.listToeicFullLrHistory.mockResolvedValue([{sessionId:"full-a",family:"A",status:"completed",listeningRaw:79,readingRaw:71,totalRaw:150,listeningEstimate:405,readingEstimate:370,totalEstimate:775,rangeLow:720,rangeHigh:830,listeningProfileVersion:1,readingProfileVersion:1,createdAt:"2026-09-01T10:00:00Z",completedAt:"2026-09-01T14:00:00Z"}]);api.getToeicFullReading.mockResolvedValue(reading);api.getToeicFullReadingAggregate.mockResolvedValue(parts);api.getToeicFullLr.mockResolvedValue(full);api.getToeicFullLrAggregate.mockResolvedValue({sessionId:"full-a",listening:[{partNumber:1,sessionId:"p1",result:{correct:5,total:6},review:[]}],reading:parts});});
describe("TOEIC parent UI",()=>{it("lists Full Reading and Full L&R parents with real totals",async()=>{render(<MemoryRouter><ToeicHistoryPage/></MemoryRouter>);expect(await screen.findByText("Full TOEIC · Form A")).toBeInTheDocument();expect(screen.getByText("150/200")).toBeInTheDocument();expect(screen.getByText("Full Reading · Form A")).toBeInTheDocument();expect(screen.getByText("71/100")).toBeInTheDocument();});it("loads Full Reading Review Mistakes and Review All from its parent",async()=>{render(<MemoryRouter initialEntries={["/toeic/reading/reading-a"]}><Routes><Route path="/toeic/reading/:id" element={<ToeicFullReadingPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Estimated Reading: 370")).toBeInTheDocument();fireEvent.click(screen.getByText("Review Mistakes"));await waitFor(()=>expect(api.getToeicFullReadingAggregate).toHaveBeenCalledWith("reading-a",true));fireEvent.click(screen.getByText("Review All"));await waitFor(()=>expect(api.getToeicFullReadingAggregate).toHaveBeenCalledWith("reading-a",false));});it("loads the 200-parent aggregate without latest-child lookup",async()=>{render(<MemoryRouter initialEntries={["/toeic/full/full-a"]}><Routes><Route path="/toeic/full/:id" element={<ToeicFullLrPage/>}/></Routes></MemoryRouter>);expect(await screen.findByText("Estimated total: 775")).toBeInTheDocument();fireEvent.click(screen.getByText("Review All"));await waitFor(()=>expect(api.getToeicFullLrAggregate).toHaveBeenCalledWith("full-a",false));expect(await screen.findByText("Total result")).toBeInTheDocument();});it("starts the requested Reading B family from the route",async()=>{api.startToeicFullReading.mockResolvedValue({...reading,sessionId:"reading-b",family:"B",status:"in_progress",answeredCount:0,estimate:null});render(<MemoryRouter initialEntries={["/toeic/reading?family=B"]}><Routes><Route path="/toeic/reading" element={<ToeicFullReadingPage/>}/><Route path="/toeic/reading/:id" element={<div>started</div>}/></Routes></MemoryRouter>);await waitFor(()=>expect(api.startToeicFullReading).toHaveBeenCalledWith("simulation","B"));});it("starts the requested Full L&R C family from the route",async()=>{api.startToeicFullLr.mockResolvedValue({...full,sessionId:"full-c",family:"C",status:"in_progress",currentSection:"listening"});render(<MemoryRouter initialEntries={["/toeic/full?family=C"]}><Routes><Route path="/toeic/full" element={<ToeicFullLrPage/>}/><Route path="/toeic/full/:id" element={<div>started</div>}/></Routes></MemoryRouter>);await waitFor(()=>expect(api.startToeicFullLr).toHaveBeenCalledWith("C"));});});
