import { BookOpen, Brain, History, Play, RotateCcw } from 'lucide-react'
import { useState } from 'react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { ErrorState, LoadingState } from '../components/PageState'
import { useReviewOverview } from '../hooks/useReviewData'
import { startReviewSession } from '../services/native'
import type { ReviewMode } from '../types'
import { formatLocalDate, humanize } from '../utils/format'
import { ConfirmationDialog } from '../components/ConfirmationDialog'
import { PageHeader, PageShell } from '../components/ProductUI'

export function ReviewPage(){
 const query=useReviewOverview();const navigate=useNavigate();const[params]=useSearchParams();const initial=params.get('mode');const[mode,setMode]=useState<ReviewMode>(initial==='vocabulary'||initial==='mistakes'?initial:'mixed');const[size,setSize]=useState<5|10|15>(10);const[busy,setBusy]=useState(false);const[actionError,setActionError]=useState<string|null>(null);const[confirmStartOver,setConfirmStartOver]=useState(false);
 if(query.loading)return <LoadingState label="Building your suggested review locally…"/>;if(query.error||!query.data)return <ErrorState message={query.error??'Review data unavailable.'} onRetry={query.reload}/>;const data=query.data;const available=mode==='vocabulary'?data.vocabulary.totalEligibleCount:mode==='mistakes'?data.recurringMistakes.confirmedCount:data.vocabulary.totalEligibleCount+data.recurringMistakes.confirmedCount;
 const start=async(startOver=false)=>{setBusy(true);setActionError(null);try{const session=await startReviewSession({mode,itemCount:size,startOver});navigate(`/review/session/${session.id}`)}catch(e){setActionError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 return <PageShell width="standard"><PageHeader eyebrow="Pedagogical review · local rules" title="Review" description="A deterministic queue built from real vocabulary and confirmed recurring mistakes. Outcomes record your choice, not right or wrong answers." />
 {data.activeSession&&<section className="mb-5 rounded-[22px] border border-[var(--accent)]/25 bg-[var(--accent)]/[.05] p-5"><p className="eyebrow">Review in progress</p><h2 className="section-title">{data.activeSession.reviewedItemCount} of {data.activeSession.actualItemCount} items reviewed</h2><div className="mt-4 flex flex-wrap gap-3"><button onClick={()=>navigate(`/review/session/${data.activeSession!.id}`)} className="button-primary">Resume Review</button><button onClick={()=>setConfirmStartOver(true)} className="button-secondary">Start Over</button></div></section>}
 <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className="glass rounded-[28px] p-5 md:p-7"><div className="flex items-center gap-2"><Play size={17} className="text-[var(--accent)]"/><h2 className="m-0 text-lg">Recommended Review Queue</h2></div><fieldset className="mt-5"><legend className="muted mb-2 text-xs">Review mode</legend><div className="grid gap-2 sm:grid-cols-3">{([['mixed','Mixed Review'],['vocabulary','Vocabulary'],['mistakes','Recurring Mistakes']] as const).map(([value,label])=><label key={value} className={`cursor-pointer rounded-xl border p-3 text-sm ${mode===value?'border-[var(--accent)]/50 bg-[var(--accent)]/[.06]':'border-white/10'}`}><input className="mr-2" type="radio" name="mode" value={value} checked={mode===value} onChange={()=>setMode(value)}/>{label}</label>)}</div></fieldset><fieldset className="mt-5"><legend className="muted mb-2 text-xs">Session size</legend><div className="flex gap-2">{([5,10,15] as const).map(value=><label key={value} className={`cursor-pointer rounded-full border px-4 py-2 text-sm ${size===value?'border-[var(--accent)]/50':'border-white/10'}`}><input className="sr-only" type="radio" name="size" checked={size===value} onChange={()=>setSize(value)}/>{value} items</label>)}</div></fieldset><div className="mt-5 rounded-2xl bg-white/[.035] p-4 text-sm"><strong>{available} eligible item{available===1?'':'s'}</strong><p className="muted mb-0 mt-1 text-xs">If fewer than {size} are available, the session uses each available item once.</p></div>{available===0?<p role="status" className="mt-4 text-sm text-amber-200">Nothing needs review yet for this mode.</p>:!data.activeSession&&<button disabled={busy} onClick={()=>void start()} className="mt-5 rounded-full bg-[var(--accent)] px-6 py-3 font-semibold text-black disabled:opacity-50">Start Review</button>}{actionError&&<p role="alert" className="text-sm text-red-200">{actionError}</p>}</section>
 <aside className="space-y-5"><section className="glass rounded-[22px] p-5"><BookOpen size={17} className="text-[var(--accent)]"/><h2 className="text-base">Items to Review</h2><dl className="grid grid-cols-2 gap-3"><Count label="New" value={data.vocabulary.newCount}/><Count label="Learning" value={data.vocabulary.learningCount}/><Count label="Vocabulary" value={data.vocabulary.totalEligibleCount}/><Count label="Mistakes" value={data.recurringMistakes.confirmedCount}/></dl></section><section className="glass rounded-[22px] p-5"><Brain size={17} className="text-[var(--accent)]"/><h2 className="text-base">Suggested focus</h2><p className="muted mb-0 text-sm">{data.suggestedFocus??'Complete an analyzed lesson to receive a suggested focus.'}</p></section></aside></div>
 <section className="glass mt-5 rounded-[24px] p-5"><div className="flex items-center gap-2"><History size={17} className="text-[var(--accent)]"/><h2 className="m-0 text-base">Recent Review Sessions</h2></div>{data.recentSessions.length===0?<p className="muted mb-0 mt-4 text-sm">No review history yet.</p>:<div className="mt-4 space-y-2">{data.recentSessions.map(item=><div key={item.id} className="flex flex-wrap justify-between gap-3 rounded-xl bg-white/[.035] p-3 text-sm"><span>{formatLocalDate(item.startedAt)} · {humanize(item.mode)}</span><span className="muted">{item.reviewedItemCount}/{item.actualItemCount} · {humanize(item.status)}</span></div>)}</div>}</section>
 <p className="muted mt-4 flex items-center gap-2 text-xs"><RotateCcw size={13}/>Review records self-assessment history only; it is not a score or SRS schedule.</p><ConfirmationDialog open={confirmStartOver} title="Start this Review over?" description="Reviewed items remain in history. A new queue will replace the current active session." confirmLabel="Start Over" danger busy={busy} onClose={()=>setConfirmStartOver(false)} onConfirm={()=>void start(true)}/></PageShell>}
function Count({label,value}:{label:string;value:number}){return <div><dt className="muted text-[10px] uppercase tracking-wider">{label}</dt><dd className="m-0 mt-1 text-xl font-semibold">{value}</dd></div>}
