import { DatabaseBackup, ExternalLink, FolderOpen, RotateCcw } from 'lucide-react'
import { useState } from 'react'
import { useDataSafety } from '../hooks/useDataSafety'

export function DataBackupSection(){
  const data=useDataSafety(); const [confirming,setConfirming]=useState<string|null>(null)
  const busy=!!data.status&&!['idle','completed','failed'].includes(data.status.operation)
  const selected=data.backups.find(item=>item.backupId===confirming)
  return <section className="glass mt-5 rounded-[28px] p-5 md:p-7" aria-labelledby="data-backup-title">
    <div className="flex flex-wrap items-start justify-between gap-4"><div className="flex min-w-0 gap-3"><DatabaseBackup className="mt-1 shrink-0 text-[var(--accent)]" size={21}/><div><p className="muted mb-2 text-xs uppercase tracking-[.18em]">Data &amp; Backup</p><h2 id="data-backup-title" className="m-0 text-lg">Protect your learning data</h2><p className="muted mb-0 mt-2 text-sm">Create a validated local snapshot of lessons, progress and settings.</p></div></div><a href="/diagnostics" className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm no-underline"><ExternalLink size={16}/>System Diagnostics</a></div>
    <div className="mt-5 flex flex-wrap gap-3"><button type="button" disabled={busy||data.loading} onClick={()=>void data.create()} className="rounded-xl bg-[var(--accent)] px-4 py-2.5 text-sm font-semibold text-black disabled:opacity-50">{data.status?.operation==='creating'||data.status?.operation==='validating'?'Creating backupâ€¦':'Create Backup'}</button><button type="button" onClick={()=>void data.openFolder()} className="flex items-center gap-2 rounded-xl border border-white/10 px-4 py-2.5 text-sm"><FolderOpen size={16}/>Open Backup Folder</button></div>
    {data.error&&<p role="alert" className="mt-4 text-sm text-red-300">{data.error}</p>}
    {data.status?.pendingRestart&&<p role="status" className="mt-4 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-3 text-sm text-amber-100">Restore is ready. Restart the app to finish safely.</p>}
    {data.restoreResult&&<p role="status" className="mt-4 text-sm text-emerald-200">{data.restoreResult.message}</p>}
    <div className="mt-5 rounded-2xl bg-white/[.03] p-4"><h3 className="m-0 text-sm">Available backups</h3>{data.loading?<p className="muted mb-0 mt-3 text-sm">Loading backupsâ€¦</p>:data.backups.length===0?<p className="muted mb-0 mt-3 text-sm">No backups created yet.</p>:<ul className="m-0 mt-3 space-y-3 p-0">{data.backups.map((backup,index)=><li key={backup.backupId} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/[.07] p-3"><div><p className="m-0 text-sm font-medium">{index===0?'Last backup':'Backup'} Â· Schema {backup.schemaVersion}</p><p className="muted mb-0 mt-1 break-all text-xs">{backup.createdAt} Â· {(backup.databaseBytes/1024).toFixed(1)} KB</p></div><button type="button" disabled={busy||!data.status?.restoreAllowed||data.status?.pendingRestart} aria-label={`Restore backup ${backup.createdAt}`} onClick={()=>setConfirming(backup.backupId)} className="flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-sm disabled:opacity-50"><RotateCcw size={15}/>Restore</button></li>)}</ul>}</div>
    {data.status?.restoreBlockReason&&<p className="muted mt-3 text-xs">{data.status.restoreBlockReason}</p>}
    <p className="muted mb-0 mt-4 text-xs">Backups contain your local learning data and are not encrypted. Keep them in a location you trust. Models, Python environments, audio, caches and logs are excluded.</p>
    {selected&&<div role="dialog" aria-modal="true" aria-labelledby="restore-confirm-title" className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-5"><div className="glass max-w-lg rounded-[28px] p-6"><h2 id="restore-confirm-title" className="mt-0 text-xl">Restore this backup?</h2><p className="muted text-sm">Restoring replaces your current learning data with the selected backup. A safety backup of your current data will be created first.</p><p className="muted break-all text-xs">{selected.createdAt}</p><div className="mt-5 flex justify-end gap-3"><button type="button" autoFocus onClick={()=>setConfirming(null)} className="rounded-xl border border-white/10 px-4 py-2">Cancel</button><button type="button" onClick={()=>{setConfirming(null);void data.restore(selected.backupId)}} className="rounded-xl bg-[var(--accent)] px-4 py-2 font-semibold text-black">Restore Backup</button></div></div></div>}
  </section>
}
