import { Check, RotateCcw, X } from 'lucide-react'
import { useEffect, useMemo, useRef, useState, type ReactNode } from 'react'
import { completeGuidedLessonStage, selectGuidedLessonExerciseAttempt, submitGuidedLessonExerciseAttempt } from '../services/native'
import type { ExerciseExpectedAnswer, ExerciseResponse, GuidedExerciseItem, GuidedExerciseStage as GuidedExerciseStageDto, GuidedExerciseSummary, GuidedLessonSession } from '../types'

interface Props { stage:GuidedExerciseStageDto;session:GuidedLessonSession;stageId:string;update:(session:GuidedLessonSession)=>void;reportError:(message:string|null)=>void }

export function GuidedExerciseStage({stage,session,stageId,update,reportError}:Props){
  const item=stage.items[stage.currentExerciseIndex]??null
  const[busy,setBusy]=useState(false);const[displayedAttemptId,setDisplayedAttemptId]=useState<string|null>(null)
  const[single,setSingle]=useState('');const[multiple,setMultiple]=useState<string[]>([]);const[text,setText]=useState('');const[order,setOrder]=useState<string[]>([]);const[matches,setMatches]=useState<Record<string,string>>({})
  const resultRef=useRef<HTMLDivElement>(null);const promptRef=useRef<HTMLHeadingElement>(null)
  const displayed=item?.attempts.find(value=>value.attemptId===displayedAttemptId)??null
  const resetAnswer=()=>{setSingle('');setMultiple([]);setText('');setOrder([]);setMatches({})}
  useEffect(()=>{resetAnswer();setDisplayedAttemptId(item?.attempts.at(-1)?.attemptId??null);queueMicrotask(()=>promptRef.current?.focus())},[item?.exerciseId,item?.attempts])
  useEffect(()=>{if(displayedAttemptId)resultRef.current?.focus()},[displayedAttemptId])
  const canSubmit=useMemo(()=>{if(!item||displayed)return false;switch(item.exerciseType){case'single_choice':return!!single;case'multiple_select':return multiple.length>0;case'fill_blank':case'short_answer_exact':return!!text.trim();case'word_order':return order.length===item.payload.tokens.length;case'matching':{const values=Object.values(matches);return values.length===item.payload.leftItems.length&&new Set(values).size===values.length}}},[displayed,item,matches,multiple.length,order.length,single,text])
  if(stage.summary)return <ExerciseSummary summary={stage.summary} busy={busy} complete={async()=>{if(busy)return;setBusy(true);reportError(null);try{update(await completeGuidedLessonStage(session.id,stageId))}catch(value){reportError(message(value))}finally{setBusy(false)}}}/>
  if(!item)return <p role="alert">Exercise progress is unavailable.</p>
  const response=():ExerciseResponse=>{switch(item.exerciseType){case'single_choice':return{exerciseType:'single_choice',value:{optionId:single}};case'multiple_select':return{exerciseType:'multiple_select',value:{optionIds:multiple}};case'fill_blank':return{exerciseType:'fill_blank',value:{text}};case'word_order':return{exerciseType:'word_order',value:{tokenIds:order}};case'matching':return{exerciseType:'matching',value:{pairs:item.payload.leftItems.map(left=>({leftId:left.itemId,rightId:matches[left.itemId]}))}};case'short_answer_exact':return{exerciseType:'short_answer_exact',value:{text}}}}
  const submit=async()=>{if(!canSubmit||busy)return;setBusy(true);reportError(null);try{const submissionId=globalThis.crypto?.randomUUID?.()??`submission-${Date.now()}-${Math.random().toString(36).slice(2)}`;const next=await submitGuidedLessonExerciseAttempt(session.id,stageId,item.exerciseId,submissionId,response());update(next);const content=next.activeStage?.content;if(content?.kind==='exercise'){const current=content.stage.items[content.stage.currentExerciseIndex];setDisplayedAttemptId(current?.attempts.at(-1)?.attemptId??null)}}catch(value){reportError(message(value))}finally{setBusy(false)}}
  const select=async()=>{if(!displayed||busy)return;setBusy(true);reportError(null);try{update(await selectGuidedLessonExerciseAttempt(session.id,stageId,item.exerciseId,displayed.attemptId))}catch(value){reportError(message(value))}finally{setBusy(false)}}
  return <div className="mt-6">
    <div className="mb-4 flex flex-wrap items-center justify-between gap-3"><p className="eyebrow m-0">Exercise {stage.currentExerciseIndex+1} of {stage.items.length}</p><span className="muted text-sm">Attempts: {item.attempts.length}</span></div>
    <article className="rounded-2xl border border-white/10 bg-white/[.025] p-5 md:p-6">
      <h3 ref={promptRef} tabIndex={-1} className="m-0 break-words text-xl outline-none">{item.prompt}</h3>
      {item.instructions&&<p className="muted mb-0 mt-2 text-sm">{item.instructions}</p>}
      {item.hint&&<details className="mt-4 rounded-xl border border-white/10 p-3"><summary className="cursor-pointer font-medium">Show hint</summary><p className="mb-0 mt-2 text-sm">{item.hint}</p></details>}
      <div className="mt-5"><ExerciseInput item={item} disabled={!!displayed||busy} single={single} setSingle={setSingle} multiple={multiple} setMultiple={setMultiple} text={text} setText={setText} order={order} setOrder={setOrder} matches={matches} setMatches={setMatches}/></div>
      {!displayed&&<button type="button" className="button-primary mt-5" disabled={!canSubmit||busy} onClick={()=>void submit()}>{busy?'Checking locally…':'Submit answer'}</button>}
      {displayed&&<div ref={resultRef} tabIndex={-1} role="status" aria-live="polite" className={`mt-5 rounded-2xl border p-5 outline-none ${displayed.correct?'border-emerald-400/35 bg-emerald-400/[.05]':'border-amber-300/35 bg-amber-300/[.05]'}`}><div className="flex items-center gap-2 text-lg font-semibold">{displayed.correct?<><Check aria-hidden="true"/>Correct</>:<><X aria-hidden="true"/>Not quite</>}</div><p>{displayed.feedback}</p>{displayed.explanation&&<p className="muted text-sm">{displayed.explanation}</p>}<ExpectedAnswer value={displayed.expectedAnswer}/><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="button-secondary" disabled={busy} onClick={()=>{setDisplayedAttemptId(null);resetAnswer()}}><RotateCcw size={16}/>Try Again</button><button type="button" className="button-primary" disabled={busy} onClick={()=>void select()}>{busy?'Saving…':'Continue'}</button></div></div>}
    </article>
    <p className="muted mt-4 text-sm">Correctness is feedback, not a progression gate. You may retry or continue after any submitted answer.</p>
  </div>
}

interface InputProps{item:GuidedExerciseItem;disabled:boolean;single:string;setSingle:(v:string)=>void;multiple:string[];setMultiple:(v:string[])=>void;text:string;setText:(v:string)=>void;order:string[];setOrder:(v:string[])=>void;matches:Record<string,string>;setMatches:(v:Record<string,string>)=>void}
function ExerciseInput({item,disabled,single,setSingle,multiple,setMultiple,text,setText,order,setOrder,matches,setMatches}:InputProps){
  if(item.exerciseType==='single_choice')return <fieldset disabled={disabled} className="grid gap-3 border-0 p-0"><legend className="sr-only">Choose one answer</legend>{item.payload.options.map(option=><label key={option.optionId} className="flex min-w-0 cursor-pointer items-start gap-3 rounded-xl border border-white/10 p-3"><input type="radio" name={`exercise-${item.exerciseId}`} value={option.optionId} checked={single===option.optionId} onChange={()=>setSingle(option.optionId)}/><span className="break-words">{option.text}</span></label>)}</fieldset>
  if(item.exerciseType==='multiple_select')return <fieldset disabled={disabled} className="grid gap-3 border-0 p-0"><legend className="sr-only">Choose all correct answers</legend>{item.payload.options.map(option=><label key={option.optionId} className="flex min-w-0 cursor-pointer items-start gap-3 rounded-xl border border-white/10 p-3"><input type="checkbox" checked={multiple.includes(option.optionId)} onChange={()=>setMultiple(multiple.includes(option.optionId)?multiple.filter(id=>id!==option.optionId):[...multiple,option.optionId])}/><span className="break-words">{option.text}</span></label>)}</fieldset>
  if(item.exerciseType==='fill_blank')return <label className="block"><span className="sr-only">Fill in the blank</span><span className="flex flex-wrap items-center gap-2 text-lg"><span>{item.payload.prefix}</span><input aria-label="Fill in the blank" className="min-w-36 flex-1 rounded-xl border border-white/15 bg-black/20 px-3 py-2" maxLength={200} disabled={disabled} value={text} onChange={event=>setText(event.target.value)}/><span>{item.payload.suffix}</span></span></label>
  if(item.exerciseType==='short_answer_exact')return <label className="block text-sm font-medium">Your short answer<input className="mt-2 block w-full rounded-xl border border-white/15 bg-black/20 px-3 py-2" maxLength={200} disabled={disabled} value={text} onChange={event=>setText(event.target.value)}/></label>
  if(item.exerciseType==='word_order'){const available=item.payload.tokens.filter(token=>!order.includes(token.tokenId));return <div><p id="available-word-label" className="text-sm font-medium">Available words</p><div aria-labelledby="available-word-label" className="flex flex-wrap gap-2">{available.map(token=><button type="button" className="button-secondary" disabled={disabled} key={token.tokenId} onClick={()=>setOrder([...order,token.tokenId])}>{token.text}</button>)}</div><p id="answer-word-label" className="mt-5 text-sm font-medium">Your answer</p><div aria-labelledby="answer-word-label" className="min-h-14 rounded-xl border border-dashed border-white/20 p-3"><div className="flex flex-wrap gap-2">{order.map(id=>{const token=item.payload.tokens.find(value=>value.tokenId===id)!;return <button type="button" className="button-secondary" disabled={disabled} key={id} aria-label={`Remove ${token.text}`} onClick={()=>setOrder(order.filter(value=>value!==id))}>{token.text}</button>})}</div></div><button type="button" className="mt-3 text-sm underline" disabled={disabled||order.length===0} onClick={()=>setOrder([])}>Clear answer</button></div>}
  const matching=item as Extract<GuidedExerciseItem,{exerciseType:'matching'}>
  return <fieldset disabled={disabled} className="grid gap-4 border-0 p-0"><legend className="sr-only">Match each item</legend>{matching.payload.leftItems.map(left=>{const used=new Set(Object.entries(matches).filter(([id])=>id!==left.itemId).map(([,id])=>id));return <label key={left.itemId} className="grid min-w-0 gap-2 sm:grid-cols-[minmax(0,1fr)_minmax(0,1fr)] sm:items-center"><span className="break-words font-medium">{left.text}</span><select aria-label={`Match for ${left.text}`} className="min-w-0 rounded-xl border border-white/15 bg-[var(--surface)] px-3 py-2" value={matches[left.itemId]??''} onChange={event=>setMatches({...matches,[left.itemId]:event.target.value})}><option value="">Choose a match</option>{matching.payload.rightItems.map(right=><option key={right.itemId} value={right.itemId} disabled={used.has(right.itemId)}>{right.text}</option>)}</select></label>})}</fieldset>
}

function ExpectedAnswer({value}:{value:ExerciseExpectedAnswer}){let content:ReactNode;if(value.kind==='single_choice')content=value.option.text;else if(value.kind==='multiple_select')content=value.options.map(option=>option.text).join('; ');else if(value.kind==='fill_blank'||value.kind==='short_answer_exact')content=value.answer;else if(value.kind==='word_order')content=value.tokens.map(token=>token.text).join(' ');else content=<ul className="mb-0 mt-2 pl-5">{value.pairs.map(pair=><li key={pair.left.itemId}>{pair.left.text} — {pair.right.text}</li>)}</ul>;return <div className="mt-4 rounded-xl bg-black/15 p-3"><strong>Expected answer</strong><div className="mt-1 break-words">{content}</div></div>}
function ExerciseSummary({summary,busy,complete}:{summary:GuidedExerciseSummary;busy:boolean;complete:()=>Promise<void>}){return <section className="mt-6 rounded-2xl border border-white/10 p-6" aria-labelledby="exercise-summary-title"><p className="eyebrow">Stage summary</p><h3 id="exercise-summary-title" className="text-2xl">Exercises completed</h3><dl className="grid gap-3 sm:grid-cols-3"><div><dt className="muted text-sm">Selected answers</dt><dd className="m-0 text-2xl font-semibold">{summary.exerciseCount}</dd></div><div><dt className="muted text-sm">Correct selected answers</dt><dd className="m-0 text-2xl font-semibold">{summary.selectedCorrectCount} of {summary.exerciseCount}</dd></div><div><dt className="muted text-sm">Total attempts</dt><dd className="m-0 text-2xl font-semibold">{summary.totalAttemptCount}</dd></div></dl><p className="mt-4"><strong>{summary.accuracyPercent}% Exercise Accuracy</strong></p><p className="muted text-sm">This practice accuracy is not a lesson score, level, CEFR result or pass/fail decision.</p><button type="button" className="button-primary mt-3" disabled={busy} onClick={()=>void complete()}>{busy?'Completing…':'Complete Exercise Stage'}</button></section>}
function message(value:unknown){return value instanceof Error?value.message:String(value)}
